### ISSUE TITLE
Crafting support

### ISSUE THREAD

**Issue by xijio** [ravahn/FFXIV_ACT_Plugin#10]
Okay this ones a little wacky I'll admit.  But I've been crafting a lot lately and a lot of times I am doing lots of math in my head and openeing calculators for things like how many hits w/ ingenuity / ingenuity ii  a careful synth will take to finish it.  It'd be cool to use the parse data from crafting to know how much each type of synthesis would do given the current stats and how much quality increase each quality move would do.  maybe this is just too crazy, but it'd be really freakin cool

**Comment by ravahn** [comment]
I've decided not to add crafting stats to the logs.  I believe the network packet data exposes some crafting information, but the plugin is going to focus only on its core activity of parsing encounters.
