### ISSUE TITLE
Direct damage calculated wrong

### ISSUE THREAD

**Issue by valarnin** [ravahn/FFXIV_ACT_Plugin#103]
Direct damage abilities seem to be calculated significantly wrong. Take this log line:

21|2017-07-26T21:39:01.8410000-04:00|###|char name|1F|Heavy Swing|###|Blathering Buzzfly|710003|509|1C|80001F|0|0|0|0|0|0|0|0|0|0|0|0|15534|24302|10190|10190|1000|1000|-118.5779|582.1775|12.1504|36728|39824|4560|4560|760|1000|-119.6592|581.2053|12.52547|90afc221a801a5cae0a0ee4674185256

This is calculating as 173 damage in the logs. The damage in the logs (per a few lines later):

00|2017-07-26T21:39:01.0000000-04:00|082b||You use Heavy Swing.|a91cd5e3064d52f8ae0877c99f934810
00|2017-07-26T21:39:01.0000000-04:00|0aa9||   The blathering buzzfly takes 1289 damage.|5fb6ad9b35b59ca4b1371b7a25a27c60

This corresponds to hex 0x509 from the log line. This is being displayed as 173 damage in the parser, though.

![image](https://user-images.githubusercontent.com/6119598/28740098-e5f3e826-73ce-11e7-9680-8702d950cf4e.png)

ACT version 3.3.0 r254
Plugin version 1.5.1.5

**Comment by Ihysoal** [comment]
This doesn't just happen with direct damage, also happens with summoner dots. Spotted it testing the potency of bane spreading

[16:20:28.798] 18:DoT Tick on Striking Dummy for 2955 damage.
[16:20:28.798] 18:DoT Tick on Striking Dummy for 2362 damage.

![image](https://user-images.githubusercontent.com/124339/29217371-d8ba2e84-7eb1-11e7-9b17-d50e1801ac40.png)

![image](https://user-images.githubusercontent.com/124339/29217382-e574b7ac-7eb1-11e7-9e39-cca3c8a1c34a.png)



ACT version 3.3.0 r255
Plugin version 1.5.1.5
