### ISSUE TITLE
Summoner DoT Potencies Outdated

### ISSUE THREAD

**Issue by CyberForte** [ravahn/FFXIV_ACT_Plugin#109]
Hey, not really sure the proper etiquette on here, but I noticed an issue with summoner dot potencies. I think the plugin is still simulating with the Bio III/Miasma III potencies from patch 4.0, instead of the +25% buff from 4.06. I noticed this because there was a significant inconsistency between the FFlogs and ACT dps for a summoner in my raid group, and after comparing the two, I found that the difference was in the percentage contribution from the dots. I confirmed this issue by comparing multiple ACT parses to FFlogs, and the inconsistency was always present, always from dots, and always on the same order of magnitude. Since dots don't appear in the combat log, I recall that they have to be simulated and both dots had their potencies updated from 40 to 50 on August 8th (http://na.finalfantasyxiv.com/lodestone/topics/detail/28053f7fa83022c6b203fdcfbd32b042fee8619c ).

Thanks!

**Comment by ravahn** [comment]
Apologies for the delay, an update to fix this will be coming shortly.
