### ISSUE TITLE
PartyList signature error

### ISSUE THREAD

**Issue by arithx** [ravahn/FFXIV_ACT_Plugin#116]
After updating I'm seeing the error pop up:

`ERROR: Unable to find Signature for [PartyList]` followed by a lot of `Error: Unable to read signature [PartyList]`.

Running on DX9 and do have cross server friends (not sure if this matters but didn't test the update until after I'd added people).

**Comment by jhelwig** [comment]
[v1.5.1.8](https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/v1.5.1.8) doesn't support DX9.
