### ISSUE TITLE
Not displaying Job

### ISSUE THREAD

**Issue by Zigglett** [ravahn/FFXIV_ACT_Plugin#118]
Parser will parse damage, but it is either not recording or not displaying jobs. 
here's what I mean:
https://imgur.com/a/Ca9oG
https://imgur.com/a/gQLt4

I'm using version 1.5.1.9

**Comment by jun3270tr** [comment]
The versions 1.5.1.8 and 1.5.1.9 are for DX11; DX9-support will eventually get added and it should also fix uploading parses.

**Comment by Zigglett** [comment]
Switched to DX11, problem solved, thanks!
