### ISSUE TITLE
Unable to read signature

### ISSUE THREAD

**Issue by splittingskies** [ravahn/FFXIV_ACT_Plugin#121]
Not sure if this is a problem on my end, but I keep getting the message in the title. Updated ACT and then the plugin to 1.5.1.9 but it still has the error message.

**Comment by insomxd** [comment]
getting the same (or similar issue) 
just checked Plugins > FFXIV Settings > Parser Messages and I have this as an error,

ERROR: Unable to find Signature for [PartyList].
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]

This error just keeps repeating

**Comment by Alyeska70** [comment]
Same error since patch 4.1., plugin 1.5.1.9
parsing myself is fine, parsing others in group/alliance does not work
it can parse the bosses/mobs. furthermore it looks like it can recognize somewhat the healer, as i get the HPS.

**Comment by splittingskies** [comment]
Been having the same issues as the comments above, attempted to uninstall ACT and remove/delete the plugin. Then reinstalled ACT and updated it to the latest version before adding/enabling plug in, ACT asks if I want to update which I hit yes then I get the following fatal error: 

Object reference not set to an instance of an object
ACTs error log will contain more debugging information.

Which is exactly what I get also with the above comments

**Comment by insomxd** [comment]
should mention that this is only when the game is run on dx9, no problems on dx11, so i would recommend launching the game through DX11, this fixed the problem for me

**Comment by ravahn** [comment]
dx9 update will be out soon.
