### ISSUE TITLE
FFXIV_ACT_Plugin 1.5.1.9

### ISSUE THREAD

**Issue by bon3z91** [ravahn/FFXIV_ACT_Plugin#122]
Hi Ravahn,

I keep getting this error stating,
ERROR: Unable to find Signature for [PartyList].
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [PartyList]
![act_error](https://user-images.githubusercontent.com/32776336/31556440-a43f34ea-b077-11e7-8f13-428c8de01c76.PNG)

As stated in the image in the url. I can parse normally on rainbowmage but it throws a very annoying error when I switch off my ACT. Image or the error is as below.

![act_error_2](https://user-images.githubusercontent.com/32776336/31556526-fe81bbee-b077-11e7-800c-ae68f039885a.PNG)

I've tried uninstalling and reinstalling ACT while also updating to the latest ACT version with booting up the latest version of FFXIV_ACT_Plugin 1.5.1.9. I'm clueless to how to fix this. Is there a way i can handle this error?

**Comment by DaxxTrias** [comment]
Its not updated for DX9. Run the game as DX11, or wait and hope for the plugin to be updated for DX9

**Comment by bon3z91** [comment]
My life is a lie. I was always running it on Dx9 when i had DX11 all along. Thanks for telling me this. Got my ACT up and running now with no errors. Cheers

**Comment by barsquiggle** [comment]
1.5.1.9 won't work with DX9. Gotta open the XIV launcher, go into "config" and then click the slider for DX11. Fixed my same exact problem!
