### ISSUE TITLE
Rook/Bishop Overload counting as Player Deaths

### ISSUE THREAD

**Issue by thatdudewon** [ravahn/FFXIV_ACT_Plugin#123]
The skill(s) Rook/Bishop Overload for MCH, which blows up the turret pet for high damage, adds a death count to the Player, misleading information in active parsing that the player has died multiple times when they haven't every use.

Recreation: Just use the skill and ACT will count it as a death

*Combine Pets with Owner is Enabled

**Comment by ravahn** [comment]
Next version will filter out rook/bishop overload deaths when combine pet with owner is checked.  I'll leave the rest as-is - other types of pet deaths will still appear as player deaths when combine pets with owner is enabled.

**Comment by Squall-Leonhart** [comment]
on the subject of machinest,  I don't seem to see wildfire's damage either on the target or as outgoing from my character.

**Comment by ravahn** [comment]
Need more info for wildfire help...I will mention that if network parsing is disabled, it probably wont get captured as wildfire and will appear as an unknown DoT tick.

**Comment by Squall-Leonhart** [comment]
its was getting NaN'd in ACT, i just updated the plugin and attempted to reproduce it with logging on and its now working.

sorry, late alarm, ha.

**Comment by thatdudewon** [comment]
@ravahn as of the latest update (1.5.1.10), Overload is still causing Killing marks on the Player as per the screenshot on a striking dummy [https://puu.sh/xZFrL/08210b4492.png](url)

**Comment by thatdudewon** [comment]
Heres a better screencap of multiple uses on a dummy and how it displays on a skin:
(https://puu.sh/xZFQD/85dc21c9a9.png)
(https://puu.sh/xZFUp/9f188064e0.png)

**Comment by ravahn** [comment]
This turned out to be a coding bug when I fixed it, under most scenarios (except the one I tested at the time) the code was not properly identifying the turret death lines.  This will be fixed in the next release, 1.7.2.6.
