### ISSUE TITLE
Party/Alliance Filter broke with 4.11

### ISSUE THREAD

**Issue by Squall-Leonhart** [ravahn/FFXIV_ACT_Plugin#126]
it is only tracking my dps and the HPS from healers

**Comment by Squall-Leonhart** [comment]
MEMORY ERROR: 254|2017-10-21T16:32:18.0000000+11:00|Bad FFXIV Packet header: 485454502F312E3120323030204F4B0D0A4163636570742D
MEMORY ERROR: 254|2017-10-21T16:32:18.0000000+11:00|Correcting network buffer, Discarding [788] of [788] bytes from Connection 117.18.237.29:80 -> 192.168.1.3:10080: 485454502F312E3120323030204F4B0D0A4163636570742D52616E6765733A20
Invalid log line: 03|0001-01-01T00:00:00.0000000|f0001103|O��!
ERROR: Invalid Line type '1��Q.��|30|f2|12fd6fd0|140e03f0|12a04d22|726530f4c8f4bad3040d02da5cdb1155
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type '1��Q.��|30|f2|12fd6fd0|140e03f0|12a04d22|7eb8cad2b74530321a4fe4868947e13b
Invalid log line: 03|0001-01-01T00:00:00.0000000|ffee2f13|���
ERROR: Invalid Line type ��|20|e0|10ff720e|d020f37|ef3200ee|57fc2c0de73623950804be7d2e24ce19
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type ��|20|e0|10ff720e|d020f37|ef3200ee|a691a4ec1942d6673054a5e9252d0eff
ERROR: [00:00:00.000] 03:, Could not find any recognizable digits., StackTrace=   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToByte(String value, Int32 fromBase)
   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
Invalid log line: 03|0001-01-01T00:00:00.0000000|f0251d02|�R�=p��
ERROR: Invalid Line type |1e|e0|bf031e80|10040c20|10e1420b|c19fa441f2598345501bda5cdc43c42c
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type |1e|e0|bf031e80|10040c20|10e1420b|8a712951e4fd40c3562f11aaf99395f8
Invalid log line: 03|0001-01-01T00:00:00.0000000|e04a03d|
ERROR: Invalid Line type � �b��$%�>�3�|30|14|22006de|e8274527|df30d0d8|88e08dffa3d220970874bef656b1c5fc
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type � �b��$%�>�3�|30|14|22006de|e8274527|df30d0d8|dccae0c72d219590236ce983cc15fbbd
Invalid log line: 03|0001-01-01T00:00:00.0000000|1fe74de3|<�?�N�O�@�O�O�@�P�0� �1�P�1�2�r�A�B�D�5��
ERROR: Invalid Line type |33|15|fd30010e|3fc43ef|fa03ff0|6a37b716ebda744cecc23a621d9ddd75
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type |33|15|fd30010e|3fc43ef|fa03ff0|577890dfe408de7db4b8228a93929371
Invalid log line: 03|0001-01-01T00:00:00.0000000|7c409ed8|_�=�m�<
ERROR: �#<�I?��@��@�![B���BZe����zS.�j�~�\=
ERROR: Invalid Line type �#<Uzh?|3f|60|273f490f|104101d2|7c000000|5a47f2756827cbed8c2ed2b1124250f6
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: �#<�I?��@��@�![B���BZe����zS.�j�~�\=
ERROR: Invalid Line type �#<Uzh?|3f|60|273f490f|104101d2|7c000000|c479011224f01942d41af4cba14d369a
Invalid log line: 03|0001-01-01T00:00:00.0000000|673edbe9|G
ERROR: Invalid Line type ���>�˄<|0|0|3059b07|0|ffc2054d|6ea29b20a058bcffdf949c00fe68e29e
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type ���>�˄<|0|0|3059b07|0|ffc2054d|050d6bb4d10fe412c6183baf4c342eac
Invalid log line: 03|0001-01-01T00:00:00.0000000|f6dc02fe|#�S
ERROR: Invalid Line type �.�Q�%�2��P�|14|f4|e40c02ed|9230000|1f2101fd|e3a5e1a2df695fb92899900922e50492
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type �.�Q�%�2��P�|14|f4|e40c02ed|9230000|1f2101fd|58ca602abf5e0ff4e00039d38e9c19ba
Invalid log line: 03|0001-01-01T00:00:00.0000000|1e000ff5| �-���?�^���1��Ϯ��1��#
ERROR: Invalid Line type �7/���c/�=�3��2�A 0�|2|bf|e00efe31|d9007901|e30e000|0eb3bbd6689851fc1a07ef4f1a3dc309
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type �7/���c/�=�3��2�A 0�|2|bf|e00efe31|d9007901|e30e000|ccc35cf29752242fb12ec106e337a984
Invalid log line: 03|0001-01-01T00:00:00.0000000|dfcf4fd|��
ERROR: 2�#�.��o��"�>��
ERROR: Invalid Line type ���-|0|3|d30f00d|35e03b14|e30c1f06|1259822e6a6c01559bbd46c024344d4c
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: 2�#�.��o��"�>��
ERROR: Invalid Line type ���-|0|3|d30f00d|35e03b14|e30c1f06|b4bf03c2b98f56fdccfb612bdda20499
Invalid log line: 03|0001-01-01T00:00:00.0000000|4f00c14|
ERROR: Invalid Line type ��|0|f|10f0f01|0|bf3002f0|bf005ed24692e7df966f738f4e8dc1b4
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type ��|0|f|10f0f01|0|bf3002f0|e69ba26632e1345e7047868abd4a3f30
Invalid log line: 03|0001-01-01T00:00:00.0000000|fefd6101|S
ERROR: Invalid Line type �?��D��?��S|ed|0|ffc90010|1dfdc|1006ef|e477c9434616ef2b4af650cdf2dfb406
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type �?��D��?��S|ed|0|ffc90010|1dfdc|1006ef|9301d4d6983ce631376def00ddb6febb
Invalid log line: 03|0001-01-01T00:00:00.0000000|5002ef50|�#�@3��A�@� ��3�.�.�/��/���
ERROR: {
ERROR: Invalid Line type ��1?��?�!�`��0��@�|ea|31|ff0e923|4000e922|1c30e00|f49db41b16efe0f1eef6272aa6798412
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: {
ERROR: Invalid Line type ��1?��?�!�`��0��@�|ea|31|ff0e923|4000e922|1c30e00|0e57ab621497c7f094dcd48c7384e8d1
ERROR: [00:00:00.000] 03:, Could not find any recognizable digits., StackTrace=   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToByte(String value, Int32 fromBase)
   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
Invalid log line: 03|0001-01-01T00:00:00.0000000|e10bf10|� ���t��
ERROR: Invalid Line type �5�a�-�@�|4|d0|b01c040d|c030f2ad|af1f012|81bbc0a5860a46f2b0982fba8c89586b
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type �5�a�-�@�|4|d0|b01c040d|c030f2ad|af1f012|fac89f28ee382f9d3a0d43106d516701
Invalid log line: 03|0001-01-01T00:00:00.0000000|52018e3f|./�
ERROR: Invalid Line type �#'��21|17|c1|e1310a0|e8220321|a05f30e6|47ed72a2ea3d3fd17f1070530fcaa65e
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type �#'��21|17|c1|e1310a0|e8220321|a05f30e6|97b6530298e16f3231cde038ec740627
Invalid log line: 03|0001-01-01T00:00:00.0000000|e06e03ff|/�@�#��� 
ERROR: Invalid Line type �����%� �1�|77|1d|1f67a00|216f0af|56018f05|2b098a66ee005d2cb3f31cdd73e689e1
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type �����%� �1�|77|1d|1f67a00|216f0af|56018f05|9b84f8009eb3c8a363237671579f64c7
Invalid log line: 03|0001-01-01T00:00:00.0000000|fe30f0fe|��!�"�� �1��"
ERROR: Invalid Line type � � ��!|0|0|0|0|1013ef0e|de47483bcb54d23d9f09722646c55f39
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type � � ��!|0|0|0|0|1013ef0e|923e3ff7ebefef6a6a44b61baae8fe83
Invalid log line: 03|0001-01-01T00:00:00.0000000|af0030f0|�
ERROR: #����4���!
ERROR: Invalid Line type �?�?�`��0� �@�|fe|1e|ee1e010e|ef0df20e|ec129f00|684fd6e843b3c85c80237de01d5500e4
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: #����4���!
ERROR: Invalid Line type �?�?�`��0� �@�|fe|1e|ee1e010e|ef0df20e|ec129f00|991d3fce346738a16ccab3651a39ccf8
Invalid log line: 03|0001-01-01T00:00:00.0000000|1e000ff5| �-���?�^���1��Ϯ��1��#
ERROR: Invalid Line type �7/���c/�=�3��2�A 0�|2|bf|e00efe31|d9007901|e30e000|f9ef33d5682b42500ff860223353c9a7
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type �7/���c/�=�3��2�A 0�|2|bf|e00efe31|d9007901|e30e000|55602eb1e9c038fc26530447bcde49d6
Invalid log line: 03|0001-01-01T00:00:00.0000000|471d0220|�
ERROR: Invalid Line type M��� R#�/|dc|bd|43e745e7|e0dcdffe|f612c700|f5518450e73a97ec9d5c02f4f9c19b3c
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type M��� R#�/|dc|bd|43e745e7|e0dcdffe|f612c700|e0b92347c452a4142bce164076d3b44f
ERROR: [00:00:00.000] 03:, Could not find any recognizable digits., StackTrace=   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToByte(String value, Int32 fromBase)
   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
Invalid log line: 03|0001-01-01T00:00:00.0000000|1f043db2|O��?�2�"^�
ERROR: Invalid Line type �O�-�"���|2f|14|3c00fb10|2d01fa31|2ff21ce0|1dfc30c2e484f4fd26d99e336ab78e56
ERROR: [00:00:00.000] 04:, Index was outside the bounds of the array., StackTrace=   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: Invalid Line type �O�-�"���|2f|14|3c00fb10|2d01fa31|2ff21ce0|8c3622df71e2b71dabcbe92cbe9a6d02
Invalid log line: 03|0001-01-01T00:00:00.0000000|33243425|���'0
ERROR: ��"!"
ERROR: Invalid Line type ��"�|dd|f0|ef0000|fa44e746|3231d0fe|5b92b63cea8a10270264e9abab853bf0

**Comment by Squall-Leonhart** [comment]
Looks like a random thing, it started working after restarting ACT, but then closing ACT raised a memory error from ACT.

**Comment by ravahn** [comment]
Can you test with the just-released version, v1.6.1.1?  At least, most of those errors should go away.

I did update and test the party/alliance detection in v4.11 for both dx9 and dx11 versions.  If is still happening, let me know and I'll take another look.

**Comment by Rhess86** [comment]
Party filter is broken on dx9 with this new update.

**Comment by Dajova** [comment]
Can confirm, was broken for me as well and reinstalling the plugin fixed the errors. Something spooking in the background?
