### ISSUE TITLE
Encounters stopped populating 1.6.1.3 while Battleping VPN is connected

### ISSUE THREAD

**Issue by Justincredible004** [ravahn/FFXIV_ACT_Plugin#129]
My encounters stopped populating after updating to 1.6.1.3 with no errors reported and a successful connection test with the game. After extensive self checking on my end and swapping , I found that the only thing that would allow ACT to populate was running the FFXIV without the use of Battleping. This has not been a problem for many months until 1.6.1.3. I lastly tried updating to the most recent (1.6.1.5) and this also presented the same problem.

Is there anything I can do or provide any other information that could possibly help resolve this?

Thank you for all your great work!

**Comment by ravahn** [comment]
Can you email me a log using battleping with version 1.6.1.5 so I can look at the data it detects?  Ravahn (at) hotmail.com.  Don't even need to fight anything, I'm just looking for all the status messages about detected network connections and what interface it listens on.

Also, can you try manually selecting an IP address from the ffxiv settings tab with battleping running, and let me know if that helps?  Or deselect it if it was already set.

**Comment by ravahn** [comment]
Just released v1.6.1.6, please give it a try.  It does work with BP for me now, but I'd like to hear that it's working for others as well.

**Comment by Justincredible004** [comment]
That did the trick! It works like a charm for me now. Thanks for your hard work man. Much appreciated. For me, consider this issue resolved.
