### ISSUE TITLE
Parse stop when switching characters

### ISSUE THREAD

**Issue by Revnn** [ravahn/FFXIV_ACT_Plugin#131]
As title says, whenever i swap characters i have to go into the plugin conf and hit Refresh list on the Process ID. Mine is set to automatic but i still need to do this every time. Wasn't like this before and i'm not sure if its intended. It's not a big deal, just thought i let you know. DX9 btw.

**Comment by ravahn** [comment]
I've heard other similar reports but I just can't seem to reproduce it, even in DX9.  Can you tell me anything else you have running - antivirus, firewall, VPN/Proxy?  Other ACT plugins?

**Comment by Rhess86** [comment]
Ok, i found the culprit for you, its pingzapper, which uses port 443. Tested with and without and i only need to refresh with pz on.

**Comment by ravahn** [comment]
I will give pingzapper a try, thanks for pointing me in that direction.  I found bugs related to listening on the wrong interface potentially when logging out / logging in with certain VPNs, and also another for when you completely restart the game.  Fix is being tested, once it goes out I hope you can test again and let me know if it solves the problem.

**Comment by Rhess86** [comment]
Sure, as soon the update is released i'll test it out.

**Comment by Squall-Leonhart** [comment]
I'm seeing it on WTFast as well.

**Comment by Rhess86** [comment]
Tested with the new release but the problem persists with pingzapper.

**Comment by ravahn** [comment]
The process detection has been completely rewritten, and network IP filtering has been modified to always filter based on the selected process (automatic or manual).  I think this is resolved now, but I can't reinstall them to re-test it.
