### ISSUE TITLE
does new version use right crit formula?

### ISSUE THREAD

**Issue by botpig** [ravahn/FFXIV_ACT_Plugin#132]
just find the dot basecrit damage x1.5not x1.4.
version 1.5.1.6

and i can't find teammate stat information in logs file.
how to  sim   dot damage

**Comment by ravahn** [comment]
That's a bug, dot base crit should be 1.4, DH 1.2, and DH+Crit should be ~1.68.  Crit multipler also scales with crit rate (not including buffs).  I'm not sure whether damage scales with DH rate similar to Crit, but I will find out.

I'm working on a revision to DoT simulator to include DH, I will fix this as well.

Teammate stat information is unfortunately not sent to the client unless they are inspected.  Simulation does not use this information, instead it uses past damage and prior/active buffs to estimate DoT tick amounts.

**Comment by ravahn** [comment]
Took a while but I released an update to the DoT simulation in Dec/Jan which reworked Crit damage multiplier, as well as added DH to DoTs.
