### ISSUE TITLE
ACT causing client to freeze?

### ISSUE THREAD

**Issue by brandoncarroll** [ravahn/FFXIV_ACT_Plugin#133]
I've encountered an issue over the last week or so, where the FFXIV client will completely freeze while running ACT. It's only happened twice, so I haven't been able to 100% confirm it's ACT causing the issue, but both times ACT was running when the freeze occurred, and both times ending the ACT task through task manager makes the game go back to normal.

It occurred once when opening a portal to Hidden Canals during a map party, and the other right after Shiva cast her ultimate in a trial. 

Is there something I can provide that would help here? Error logs or something? I'm not sure where to find them, if so.

**Comment by ravahn** [comment]
There are a couple of touchpoints between the plugin and FFXIV.  

It reads game memory using ReadProcessMemory - this should be safe unless interfered by antivirus or some other process hooking it. 


There's the clipboard - whenever an encounter ends, ACT by default copies data to the clipboard.  This can be disabled.

There's the overlays - This doesn't directly affect FFXIV, but I suspect it is possible that driver issues can be triggered by the combination FFXIV in windowed mode with overlay windows on top of it.

Lastly, there's reports on reddit of the latest fall Windows 10 update causing issues.  Might be unrelated, but disabling fps limits inside the game can help.

Best thing you can do to help is eliminate other programs interfering - discord, third-party firewall software (windows defender is fine), vpns, etc.  It's really hard to track this sort of issue down, so I appreciate you reporting.

**Comment by brandoncarroll** [comment]
Thanks, I'll try some of that to see if I can narrow down the issue. I do use Discord and WTFast when I'm raiding, which is typically when I use ACT as well. I'm starting with the clipboard option because it seems the easiest to test. I'll update with any other crashes.

**Comment by hbq0449** [comment]
I used to have the same problem before. After I disable the "copies data to the clipboard" feature, it went away. I suggest @brandoncarroll  try that first.

**Comment by ravahn** [comment]
Strange thing I discovered: FFXIV for some reason copies the clipboard contents into game memory.  I was very surprised when searching the game memory to find things I had copied onto the clipboard much earlier in the day sitting there.

This sort of thing is hard to track down, but I do recommend disabling the clipboard as hbq0449 suggested, and let me know if that resolves the problem.
