### ISSUE TITLE
XIV Plugin writes floats to logs in a locale-dependent manner

### ISSUE THREAD

**Issue by danakj** [ravahn/FFXIV_ACT_Plugin#137]
In spanish locales, the plugin will write "20.00" as "20,00", which is more correct for human readers, but makes sharing triggers or writing other plugins to parse this much harder.

This is a cause of bugs such as https://github.com/quisquous/cactbot/issues/15

An example:

[04:00:49.979] 15:1072E940:Darth Beiber:1D60:Embolden:1072E940:Darth Beiber:500020F:4D7:0:0:0:0:0:0:0:0:0:0:0:0:0:0:30848:30848:14040:14400:1000:1000:-827,2372:-598,3194:11,6:30848:30848:14040:14400:1000:1000:-827,2372:-598,3194:11,6:
[04:00:50.811] 1A:Darth Beiber gains the effect of Embolden from Darth Beiber for 20,00 Seconds. (5)

vs

[23:36:05.785] 15:106DD019:Asada Fireclaw:1D60:Embolden:106DD019:Asada Fireclaw:500020F:4D7:0:0:0:0:0:0:0:0:0:0:0:0:0:0:37427:37427:14400:13920:1000:1000:-142.7243:-122.7555:30.02:37427:37427:14400:13920:1000:1000:-142.7243:-122.7555:30.02:
[23:36:06.407] 1A:Asada Fireclaw gains the effect of Embolden from Asada Fireclaw for 20.00 Seconds. (5)

Both positions and durations get commas in some locales instead of periods.

**Comment by Squall-Leonhart** [comment]
change the decimal seperator

**Comment by Kovensky** [comment]
That is definitely the wrong approach. The setting in Region and Language Settings is for formatting values for _humans_. The ACT log is intended to be consumed by computers, not humans, and thus it should use a locale-invariant formatter.

**Comment by Squall-Leonhart** [comment]
there's no such thing as a wrong approach as long as it gets the job done.

What was the wrong approach was these regions using a comma as a decimal seperator.

**Comment by Squall-Leonhart** [comment]
But heres how to fix it, Ravahn.
https://blogs.msdn.microsoft.com/oldnewthing/20110803-00/?p=9983/

**Comment by alphaONE2** [comment]
No, these locales use commas as the radix point and periods as the digit separator. What you would write in English as 1,234.56, a Spanish speaker would write as 1.234,56. This is specifically why the SI discourages the use of digit separators in scientific works. (They recommend a space instead, to avoid ambiguity, i.e. 1 234.56 or 1 234,56.) Forcing the user to change their region and language settings, is not the way to do this.

The .Net way to do this is to specify `CultureInfo.InvariantCulture` as the `IFormatProvider` when calling any of the string formatting functions.

**Comment by Squall-Leonhart** [comment]
That's because spanish is wrong.

**Comment by danakj** [comment]
I feel like that is approaching this thread wrong..

Thanks for the info on how to resolve it alphaONE2.

**Comment by alphaONE2** [comment]
@Squall-Leonhart, That's an incredibly egotistical and anglo-centric point of view. The choice of digit separator and radix point is completely arbitrary, and usually has cultural, historic and typographic reasons which are unique to each language. In fact, there are more countries in the world that use a comma as a radix point than there are countries that use a period. Some countries don't even use commas and periods; in Switzerland they would write 1'234.56. There are also countries that group digits into groups of 4 (China), or even irregular groupings (India; 10<sup>5</sup> would be 1,00,000). All of these countries would tell you that the style we use in English is "wrong."

**Comment by Squall-Leonhart** [comment]
The reason behind the use of comma has nothing to do with culture, it was all out of fear that a * would get mistaken.

Europe jumped the gun and screwed up numerical separation, Don't SJW and create an issue where where valid criticism is employed.

**Comment by danakj** [comment]
>  Don't SJW and create an issue where where valid criticism is employed.

You're making a problem where there wasn't one. alphaONE2 is right, please don't double down on being rude about other languages' representation of numbers.

**Comment by Squall-Leonhart** [comment]
Go away SJW's.

You will not silence valid criticism on any subject.

**Comment by alphaONE2** [comment]
@Squall-Leonhart, this isn't about social justice, this about ignorance. Please at least do some research before you start saying things. The use of both the comma and the period as a radix point can be traced back to arabic, which used a mark called a separatrix ( ˌ ; U+02CC) between the units and tenths place, which was usually approximated as either a comma or a period in Europe. Different countries adopted different styles and they stuck.

**Comment by ravahn** [comment]
This is an old issue, but it should be fixed now - both buff duration and position numbers use CultureInfo.InvariantCulture for writes to the log file, and reads for the parse engine.  I'm going to close this now, but please re-open, or open a new issue if you find this was insufficient.

I chose to use culture invariant instead of using the local pc's current region because because otherwise I would need to write out the active culture as a new type of status line in the log file, and process it when the log file is read / imported.  A single log file could also contain multiple cultures if the user changes their PC settings.  Cultureinvariant is the safest way to write it for machine parsing.
