### ISSUE TITLE
Feature request: show combatant location with 'Added combatant' message

### ISSUE THREAD

**Issue by quisquous** [ravahn/FFXIV_ACT_Plugin#139]
Ability usage from network data appears to have location data in the last few fields, but the Added Combatant message just has a name.  It would be quite helpful to know the locations of Added Combatants right when they were added and not just after they used an ability, if this is something that's available.

**Comment by quisquous** [comment]
Sorry for the ping, but I wanted to mention this feature request again, in case there's any hopes of it getting in before the expansion.

Having location data for new combatants (either in the Added Combatant field or in some new log line) would be a great win for triggers.  There's a ton of things I would like to do that this would help with:
* ucob dragon placement
* finding fairies in eureka
* finding hunt targets on the map
* t13 dragon dives
* finding ba treasure chests
* uwu predation callouts
* etc etc etc

**Comment by quisquous** [comment]
Also wanted to add that listing the combatant's id would be helpful as well to differentiate mobs.

**Comment by ravahn** [comment]
This is now added, both combatant id and position.
