### ISSUE TITLE
Target / ToT / Focus all work but no mini-parser

### ISSUE THREAD

**Issue by cdmichaelb** [ravahn/FFXIV_ACT_Plugin#140]
I get this error in 'parser messages'

`ERROR:    at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
ERROR:    at Machina.RawSocket.CreateRawSocket(UInt32 address)
ERROR:    at Machina.TCPNetworkMonitor.CheckForIPChange()
ERROR: Invalid Line type    at Machina.TCPNetworkMonitor.Run()|45c05379bcb3183ec068fb9d13f3f9d7`

**Comment by ravahn** [comment]
This error usually means that ACT was not running as an Administrator.  to resolve it, when launching ACT, right-click the icon and choose the "Run as Administrator" option.
