### ISSUE TITLE
it cant work normaly at china version path 4.10

### ISSUE THREAD

**Issue by wingchaos** [ravahn/FFXIV_ACT_Plugin#141]
at china version.its path 4.10 now..
1.6.18 can read the territorylist or zonelist.but the miniparse cant.
because the name of  title  its  "最终幻想XIV"，not “FINAL FANTASY XIV”
so it cannot work - -   >_<
![image](https://user-images.githubusercontent.com/26808840/35479592-6904055a-0436-11e8-8fba-b04c4eb0b9cd.png)
if modify title to english .than it work....LOL.

**Comment by hbq0449** [comment]
I think you shouldn't close the issue. It is supposed to ask the author to make some change to solve this problem, or else other player at China will get confused. After all, not all perple can modify the process title.
