### ISSUE TITLE
Plugin does not work with FFXIV 4.2

### ISSUE THREAD

**Issue by Nan0bit** [ravahn/FFXIV_ACT_Plugin#143]
ERROR: Unable to find Signature for [Target].
ERROR: Unable to find Signature for [MobArray].
ERROR: Unable to find Signature for [ZoneID].
ERROR: Unable to find Signature for [PartyList].

**Comment by klepp0906** [comment]
this ^

ty for your work btw

**Comment by JokerKurusu** [comment]
^ same but also freezes after trying to do anything about it

**Comment by HyperMR** [comment]
yup same its driving me insane

**Comment by ravahn** [comment]
Yes, this is a known issue, being worked on.  My goal is to release an update today.  There are a number of small changes this patch that broke a bunch of different things.

**Comment by LordanS** [comment]
Thanks for your work, ravahn.

**Comment by HyperMR** [comment]
thanks man

**Comment by Citillara** [comment]
thanks too ;)

**Comment by G0li4th** [comment]
thanks !

**Comment by KarstenS123** [comment]
Thank you very much for the hard work you still investigate into the plugin.

**Comment by Nan0bit** [comment]
Fixed, closing.

Side-note: Do you have enmitySignature64? Tamanegi could use it for the Enmity plugin.

**Comment by ravahn** [comment]
Hi @Nan0bit  - I do not, but talk to the ffxiv-app team on Discord, they may have it.
