### ISSUE TITLE
Large HP causing the HP overlay background to not show.

### ISSUE THREAD

**Issue by Genesis-Nova** [ravahn/FFXIV_ACT_Plugin#144]
When using the Overlay for target HP, if a target has beyond a certain amount it'll cause the background to not show until it drops to a certain amount.
I'm not sure exactly what amount that is but its easily noticeable when it does happen.
Similar bug to #106

**Comment by Genesis-Nova** [comment]
I don't mean to bump my own post without reason, but is there any reason as to why this bug is happening? its quite noticeable now that many mobs have HP higher than the 'threshold' and causes the HP overlay to bug out so to speak.

**Comment by ravahn** [comment]
This will be fixed in the next update (see #106 )
