### ISSUE TITLE
Log fills with decompression error

### ISSUE THREAD

**Issue by yodang** [ravahn/FFXIV_ACT_Plugin#145]
After a short time parsing in v1.6.2.5, the log fills with the following error (the actual message may be slightly different because the original log was in French):

```26|2018-02-02T21:43:50.9930000+01:00|92|Protect|293,40|106D16FE||106C0F82|Sakimed Yosei|00|56702|||a50882afcab81de16a39acf52f877cdd
00|2018-02-02T21:43:50.0000000+01:00|2230||'�Sakimed YoseiSakimed Yosei'�� loses the effect of '	3� ���{���f���Sprint'��.|effb743d4e68aedfea2a06b4ec72b99e
251|2018-02-02T21:43:50.0000000+01:00|FFXIVBundleDecoder: Decompression error: System.ArgumentOutOfRangeException: Non negative number required.
Parameter name : count
   at System.IO.MemoryStream..ctor(Byte[] buffer, Int32 index, Int32 count, Boolean writable, Boolean publiclyVisible)
   at System.IO.MemoryStream..ctor(Byte[] buffer, Int32 index, Int32 count)
   at Machina.FFXIV.FFXIVBundleDecoder.DecompressFFXIVMessage(FFXIVBundleHeader& header, Byte[] buffer, Int32 offset, Int32& ffxivMessageSize)|e3b49868963f2952b8889fa9e72a9e66
251|2018-02-02T21:43:50.0000000+01:00|FFXIVBundleDecoder: Decompression error: System.ArgumentOutOfRangeException: Non negative number required.
...
```

Packets still get recorded after that but parsing stops as the log grows too quickly (Source file was nearly 500MB for 10 minutes of logs).

I may be able to provide pcap files if it can help.

**Comment by ravahn** [comment]
I think I may have tracked this down why the infinite loop is happening, but it is difficult to test.  I'm putting some code in there to fix in the next version, hopefully it solves the problem.

**Comment by ravahn** [comment]
This change went out to fix this, so I'm closing for now, but please let me know if it continues to happen.
