### ISSUE TITLE
Some of Summoner DPS not being accounted for.

### ISSUE THREAD

**Issue by Rhakun** [ravahn/FFXIV_ACT_Plugin#146]
Since the patch and updates I've noticed that ACT is not accounting for Shadow Flare damage at all. In fact it is counting it, just as a debuff/buff with no damage when I try to see what its simulated DoT is. (The damage adds up total I am pretty sure with the DoTs but if I open up with a Tri-Disaster and don't do any damage first then it doesn't count the DPS. But if I open with an attack of some sort then it will count.)   . I know DoTs are iffy to get right but since patch and everything I've noticed my DPS dropping by at least almost as much as 1k in some situations and I know they didn't nerf SMN that much... Idk if it is just SMN class that this is happening to or what. 

It also is not tracking all of Bahamuts Wyrmwaves. It only tracks about a third of those which also looks like a DPS loss on ACT. I'm not sure if all this falls within the FFXIV Plugin or ACT itself but it needs to be looked into and fixed as soon as possible please. It's a little frustrating since I main a SMN and it starting to look like it cant pull it's own weight and is gimped which is bad so now I'm healing til its fixed =\

**Comment by ravahn** [comment]
After 5.0, I spent a lot of time improving summoner simulation.  Shadow Flare is now retired, which made it a little easier, but for normal combat rotations it should be very accurate now.  I also went through all the pets and made sure they were properly tagged in all languages as pets, so they properly get combined with their owner.  And, I made 'combine pets with owner' the default selection, to help improve summoner reporting overall.
