### ISSUE TITLE
Unable to get FFXIV_ACT_Plugin working on new Windows 10 Install

### ISSUE THREAD

**Issue by rlseii** [ravahn/FFXIV_ACT_Plugin#148]
Hi, 

I'm unable to get the FFXIV parsing plugin working with ACT.

It says:

FFXIV Plugin Startup Failed. System Configuration.ConfigurationErrorsException:
Configuration system failed to initalize --->
System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime.
(C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe.Config line 3).

-I've made sure to allow ACT through the windows firewall
-I'm running Win10 with the latest .NET version
-I've unblocked the ZIP file prior to extracting it to the directory.

Any help would be appreciated, Thanks!

**Comment by ravahn** [comment]
Sorry for the late reply.  This is the first time I'm seeing this error.  If you are still having it today, my best suggestion is to re-install .Net Framework from the original Microsoft sources.  you might need to install an earlier version before 4.7.1.  I believe ACT requires .Net 4.0 compatibility still, which is now very old.  Here is a link to Microsoft's offline 4.7.1 installer:
https://www.microsoft.com/en-us/download/details.aspx?id=56116

or you can download the web version if download size is a concern:
https://www.microsoft.com/en-us/download/details.aspx?id=56115
