### ISSUE TITLE
Separate mobs with same name

### ISSUE THREAD

**Issue by philarr** [ravahn/FFXIV_ACT_Plugin#15]
Currently ACT groups all mobs under the same name into one combatant category. Is there any way the plugin can mark each combatant with an unique ID (maybe prefix names with ID) so that each individual mob will have its own separate informatio. Will be useful to see when one mob spawns and dies etc.
Thanks!

**Comment by ravahn** [comment]
Took me a while to get back into it, but I've added ActorID and TargetID to the ACT Tags property for all entries.  You should see it when I release 1.3.0.8.
