### ISSUE TITLE
Forbidden Land of Eureka registers as Rhalgar's Reach

### ISSUE THREAD

**Issue by UDK450** [ravahn/FFXIV_ACT_Plugin#150]
Eureka came out today, and I noticed that after leaving the session and pulling up my parser from the background that it had parsed it as Rhalgar's. Also, it might cause some blocking within the parser, as after I left and ran O7N it blocked and didn't parse it.

**Comment by ravahn** [comment]
I think this should be fixed now?  I'm looking at a parse that lists the zone name as "Eureka Anemos".  maybe the previous version was missing a zone listing update.  Closing, but please re-open if it still is not working with the latest (1.7.0.5) update.
