### ISSUE TITLE
Dropped winpcap support?

### ISSUE THREAD

**Issue by xbionic** [ravahn/FFXIV_ACT_Plugin#152]
Please enable winpcap support again. It was a good way to run the Plugin as non-administrator.

Thank you in advance.

**Comment by Genesis-Nova** [comment]
![Example](https://i.imgur.com/QywFcIQ.png)
Should solve your problem.

**Comment by ravahn** [comment]
Thanks Genesis-Nova, that's right.  WinPCap support wasn't dropped, I just moved the option to a 'Parse Mode' dropdown as you pointed out.
