### ISSUE TITLE
ACT don't show any data

### ISSUE THREAD

**Issue by Delvertico** [ravahn/FFXIV_ACT_Plugin#153]
Hello there, 

i updated the latest version (3.3.1) of the ACT and after the latest FF14 Patch i don't get any data in combat. The overlay shows only the message: "No data to show" 

Where i can see where the problem is?

I also tried to update the OverlayPlugin.dll and the FFXIV_ACT_Plugin.dll, run the ACT as administrator and still dont know where the problem is :/

Please help me

Thank you

**Comment by hikaru-light** [comment]
Hi Delvertico,

This plugin was updated just now.
Maybe you can use it without any problems.

This problem often happens just after FFXIV updates.
Then try again later.

**Comment by TalakinRaclaw** [comment]
I'm having an issue with ACT not showing any data.  It will show the area I am in but no parsing data.  I have updated to the recent update post FF14 patch 4.3.  After updating FF14, I of course updated ACT and it did work for a day.  Then after, it stopped working.  I can see it wanting to parse for the area (as in it shows what area I am in and is simply waiting for data).  Other players I've spoken with who have updated ACT say they have no issues. (I would include log files here but I don't know where to obtain them)
