### ISSUE TITLE
AOE abilities not tracking all targets

### ISSUE THREAD

**Issue by crowmium** [ravahn/FFXIV_ACT_Plugin#156]
Since patch 4.2 all AoE abilities are not being recorded properly. Swings and Hits are equal and AOEs against 10+ enemies are showing a DPS loss, which isn't possible given potency values. This is across all classes. It appears that ACT is only recording one instance of damage from the AOE and not the rest.

**Comment by Squall-Leonhart** [comment]
you need to post log files to make claims like this

**Comment by Nemekh01** [comment]
Testing this for Ravahn just now and things seem to be as they should be even 10+.

This was an issue early on in Stormblood with aoe messages depending on target count but not for a very long time.

**Comment by ravahn** [comment]
Yep, thank you Nemekh, I see the same on my end.  If you are using the memory mode of the plugin, this may have caused a DPS loss that could explain the problem, so I would recommend that you make sure you are using one of the two network parse modes.  If it still persists, ACT records both the in-game combat text as well as the network data for the hits.  It only uses the network data for the damage calculation, so you can count the number of  hits using the combat log and compare it to the number of hits on the ACT combat detail.  They should be identical except for a few rare cases of chatlog data not being rendered properly by the game client itself. 

Regarding swings and hits, the purpose of these in ACT is to identify accuracy, not to count the number of casts.  If you use an AOE attack, I believe that each target can independently hit or miss.  So, one AOE hitting 8 targets will be reported as 8 swings in ACT.
