### ISSUE TITLE
Main Table stops updating while streaming.

### ISSUE THREAD

**Issue by Flarestar042** [ravahn/FFXIV_ACT_Plugin#159]
I stream using OBS Studio to Twitch.  Recently I've noticed that the Main Table stops updating approximately 45-55 seconds after I start my stream.   This issue is consistently reproducible by simply starting a broadcast and entering combat.

As far as I can tell it only happens when using the WinPCap Network in Parse Mode, but unfortunately I have to do that to get the Main Table to show anything at all, as the Main Table simply doesn't populate data despite no errors if I leave it set on Network, even though I'm running as Administrator and have an exception in the Windows Firewall for ACT.  Stopping the broadcast and hitting Refresh on the Process ID list does cause the Main Table to start populating data again.

Is this just an incompatibility with OBS, or is it something with how the FFXIV Plugin is using the Win10PCap library?

**Comment by ravahn** [comment]
Reports from Discord are that users are able to use OBS with the plugin.  If this is still happening, I recommend you join the FFXIV ACT Plugin discord and ask for assistance there.  I dont use OBS but other people do, and can help walk through configuration changes or troubleshooting steps.
