### ISSUE TITLE
ODBC (SQL) data export setup error

### ISSUE THREAD

**Issue by StoneJanM** [ravahn/FFXIV_ACT_Plugin#16]
Hello. I have been trying to utilize the SQL export function but keep receiving an error when attempting to create the tables (validate table setup button).

I am on SQL Server 2008 R2 and using the below connect string:
**Driver={SQL Server Native Client 10.0};Server=XXXX;Database=FFXIV;Uid=XXXX;Pwd=XXXX;**

I am able to connect successfully. The error only appears to happen when establishing the tables, and this is the message received within the window:
**ODBC Connection Succeeded**
**ERROR [42000] [Microsoft][SQL Server Native Client 10.0][SQL Server] Incorrect syntax near ",".**

Thank you very much for looking into this! Great job on the plugin! :)

**Comment by ravahn** [comment]
We followed up in email - this is fixed by going to the Output Display -> ODBC (SQL) settings and clicking the 'Reset' button to re-enable DataSource Compatibility Hacks.
