### ISSUE TITLE
logs with a leading "1F :"

### ISSUE THREAD

**Issue by neko8** [ravahn/FFXIV_ACT_Plugin#161]
Up to version 1.6.1.x, logs with a leading "1F :" were displayed, but in the current version, this is not displayed.
Is it possible to restore the display?
If you can, thank you.

**Comment by ravahn** [comment]
I can fix this.   1F: is Gauge updates for the active player (not other people), I should be able to release in a couple of days.

**Comment by neko8** [comment]
Oh, it is amazing.
I am looking forward very much.

2018年5月24日(木) 9:15 ravahn <notifications@github.com>:

**Comment by ravahn** [comment]
This is done in 1.7.0.10, let me know if you see it after the update.

**Comment by neko8** [comment]
Thank you for your prompt response.
It is a great help.
Thank you very much.
