### ISSUE TITLE
Not working with the new patch 4.3

### ISSUE THREAD

**Issue by HyperMR** [ravahn/FFXIV_ACT_Plugin#165]

**Comment by xmindcloudx** [comment]
2nd!

**Comment by Rashid90** [comment]
ye :(

**Comment by DefenderXY** [comment]
same issue, must be the patch.

**Comment by ravahn** [comment]
yep, I'm working on it but there were some network packet changes that took a while to figure out.

I plan to release the update tomorrow (Wednesday)

**Comment by xmindcloudx** [comment]
Cool bud thanks for the hard work!

**Comment by Rangerhoe84** [comment]
Ravahn, in advance - Thanks for all the hard work!
Is the plan still to release it today? You know at what time you expect it to go live?

Thanks again!

**Comment by essjaybee** [comment]
Thanks for your work ravahn!

**Comment by swoeber** [comment]
Doing fantastic, keep up the great work!!

**Comment by DevilToGod** [comment]
Thanks a lot Ravahn for the work.

**Comment by angeleternalium** [comment]
Ravanah, do you have update it for x64 bits ?

**Comment by angeleternalium** [comment]
i can't find the link @ravahn

**Comment by Rashid90** [comment]
Ty for your time and effort bro
@ravahn

**Comment by PommeVerte** [comment]
@ravahn is there any way some of us can contribute to reduce your workload? Would perhaps making PRs against machina in the event opcodes change do anything for you? It's kind of hard to tell since plugin code is obfuscated.

**Comment by angeleternalium** [comment]
somes player have a link for a 32 bits working, dunno why, i tried but it doesn't work for me

**Comment by ravahn** [comment]
Thanks for the support! 1.7.0.9 is released.  Hopefully caught all the bugs / changes, so post a new issue if you come across new problems.

**Comment by moea-chan** [comment]
Thx buddy! Great job !!

**Comment by neoxianwu** [comment]
Thank you!!
