### ISSUE TITLE
"There is an updated version of the FFXIV parsing plugin."

### ISSUE THREAD

**Issue by Sorrydoor** [ravahn/FFXIV_ACT_Plugin#168]
I've been experiencing this since the previous update (I can't recall how I got that removed) and it's back.. Tried reinstalling the plugin through the download multiple times to no avail, and can't find the plugin through the "Get Plugins" option in ACT to try and reinstall it through that. Any help would be appreciated!

**Comment by XheonNovus** [comment]
Download the plugin from the ACT site - remove your current plugin - drop the plugin ( unblock it too ) into the folder you want to keep it in ( i just drop it into the %appdata% folder ) go into ACT browse plugin and enable it and it'll purge that 

if you're still having trouble there is a file called
" Advanced Combat Tracker.config "
inside there is a line for the plugin ( at the bottom ) of a long XML - simply purge it and save it and reload ACT - this should be last resort

**Comment by Sorrydoor** [comment]
I tried your first method and it didn't work. Still have the pop-up.

As for the last resort, do you mean the Advanced Combat Tracker.exe.config? If yes, it is a...very short XML and I don't see anything relating to the FFXIV plugin.. This is pretty much it.

`<?xml version="1.0"?>`
`<configuration>`
`	<runtime>`
`		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">`
`			<dependentAssembly>`
`				<assemblyIdentity name="Advanced Combat Tracker" publicKeyToken="a946b61e93d97868" culture="neutral"/>`
`				<bindingRedirect oldVersion="2.5.0.0-3.65535.65535.65535" newVersion="3.3.1.256"/>`
`			</dependentAssembly>`
`		</assemblyBinding>`
`	</runtime>`
`	<startup>`
`		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0,Profile=Client"/>`
`	</startup>`
`</configuration>`

**Comment by XheonNovus** [comment]
\AppData\Roaming\Advanced Combat Tracker\Config

Inside you will find a file called "Advance Combat Tracker.config "


at the bottom there is a line https://prnt.sc/jsg79f/direct
this is what is checking the plugin version if it checks this version agai

**Comment by Sorrydoor** [comment]
I'm sorry, but you're telling me to remove this line right?

![what line lah](https://user-images.githubusercontent.com/39579093/41151633-eb6b900c-6b43-11e8-9698-1d9d88c7ed11.png)

This simply removed the FFXIV plugin from ACT for me.

**Comment by Sorrydoor** [comment]
So, I somehow solved the problem (for now?). Although my main ACT folder with plugins and whatnot isn't there, there was a very old FFXIV_ACT_Plugin.dll in \AppData\Roaming\Advanced Combat Tracker\Plugins\. Deleting the .dll in that folder removed the new version alert, though putting it back didn't result in the alert coming back.. I'm still pretty confused but I'll accept it for now hahaha
