### ISSUE TITLE
"No data to show" while using Pingzapper

### ISSUE THREAD

**Issue by meciuPL** [ravahn/FFXIV_ACT_Plugin#173]
Is it normal? SpecialSellTimer works, EmnityPlugin works but my miniparser shows no data no matter what I do. Any idea? Does it only work while not using a VPN client? That'd be a bummer.

**Comment by xDemonessx** [comment]
I use ping zapper and don't have any issues. Assuming you've tried a clean install?

**Comment by meciuPL** [comment]
Yes, a full clean install.

**Comment by xDemonessx** [comment]
Make sure you're running as admin. I also use the 32 bit version. 
FFXIV should be set to Automatic process ID. 
Filter on Local IP All (Default). Make sure you have the latest version of the dll 1.7.0.11

**Comment by ravahn** [comment]
If this is still happening, I recommend joining the FFXIV plugin discord, the community there may be able to assist with diagnosing the problem.
