### ISSUE TITLE
I can't use OverlayPlugin.dll

### ISSUE THREAD

**Issue by kosalluc60** [ravahn/FFXIV_ACT_Plugin#175]
Hello there, I'm not good at english but i'll try to explain what is my problem.

Actually I want to use the parser and installed it.
I added FFIV_ACT_Plugin.dll and OverlayPlugin.dll without bug on ACT but I can't configure the OverlayPlugin.
When I try to change something like "Lock Overlay" then "Reload Overlay", I get this :

![image](https://user-images.githubusercontent.com/41551426/43049417-f4dad4b4-8df7-11e8-8b1d-0efd14808880.png)

I'm sorry, it's very long and there's a bit french but the quote says : 

Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à RainbowMage.OverlayPlugin.Overlays.MiniParseOverlay.Navigate(String url)
   à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.Button.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34014 built by: FX45W81RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Advanced Combat Tracker
    Version de l'assembly : 3.3.1.256
    Version Win32 : 3.3.1.256
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34250 built by: FX452RTMGDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
GammaJul.LgLcd
    Version de l'assembly : 1.1.3.0
    Version Win32 : 1.1.3.0
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/GammaJul.LgLcd.DLL
----------------------------------------
System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Version de l'assembly : 0.85.5.452
    Version Win32 : 0.85.5.452
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ICSharpCode.SharpZipLib.DLL
----------------------------------------
System.Runtime.Serialization
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.36213 built by: FX452RTMLDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
FFXIV_ACT_Plugin
    Version de l'assembly : 1.7.0.11
    Version Win32 : 3.3.1.256
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Machina
    Version de l'assembly : 2.1.0.1
    Version Win32 : 3.3.1.256
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Machina.FFXIV
    Version de l'assembly : 2.1.0.1
    Version Win32 : 3.3.1.256
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Xml.Linq
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
OverlayPlugin
    Version de l'assembly : 0.3.4.0
    Version Win32 : 3.3.1.256
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
OverlayPlugin.Common
    Version de l'assembly : 0.3.4.0
    Version Win32 : 0.3.4.0
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Nouveau%20dossier/OverlayPlugin.Common.dll
----------------------------------------
OverlayPlugin.Core
    Version de l'assembly : 0.3.4.0
    Version Win32 : 0.3.4.0
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Nouveau%20dossier/OverlayPlugin.Core.dll
----------------------------------------
HtmlRenderer
    Version de l'assembly : 1.0.1.8
    Version Win32 : 1.0.1.8
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Nouveau%20dossier/HtmlRenderer.dll
----------------------------------------
Xilium.CefGlue
    Version de l'assembly : 3.2272.2035.0
    Version Win32 : 3.2272.2035.0
    CodeBase : file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Nouveau%20dossier/Xilium.CefGlue.dll
----------------------------------------
Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel.Internals
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

I tried to unistall and reinstall it many and research on the net but I didn't find anything ( or I'm retarded x) ).
Thanks for the help

**Comment by xDemonessx** [comment]
This is the same issue here: https://github.com/hibiyasleep/OverlayPlugin/issues/30
You should be posting the issue on the overlayplugin repo vs this one, ravahns plugin really doesn't have anything to do with your issue.

I suggest you close this and post there.

Anyway, check on the following:
*.NET Framework 4.5 or higher installed
*the DLL is not being blocked by Windows
*There are two kinds of OverlayPlugin, x86 and x64. The plug-in will not work unless you use a file that matches the operating mode of the ACT you are using. 

https://github.com/hibiyasleep/OverlayPlugin/blob/master/README-en.md

**Comment by kosalluc60** [comment]
Oh sorry, thank you ^^
