### ISSUE TITLE
Dps and healing numbers randomly being lower

### ISSUE THREAD

**Issue by markynatorka** [ravahn/FFXIV_ACT_Plugin#176]
Hey, i dont know what exactly causes this problem, but it's very annoying for me, and I've already contacted a developer of an overlay for your plugin, and he seems to have the same problem too, so it must not only be me.

The problem itself is, is that randomly when you're in a boss fight, or just fighting in general, the data will get messed up, and show weird lower numbers than the actual numbers. Once again, i have no clue what causes this. I would appreciate some help. Thank you in advance. 
![screenshot_190](https://user-images.githubusercontent.com/42062385/43636069-56468320-9711-11e8-8e5b-c2453811a3cf.png)
![ohv2ghl](https://user-images.githubusercontent.com/42062385/43636104-6fe784be-9711-11e8-99b2-5b9581df4d73.png)
![2018-07-31_00-08-50](https://user-images.githubusercontent.com/42062385/43636142-8bdb6794-9711-11e8-8125-0c59b3cc0bef.png)
![optrmpbt2znj_firefox_2018-08-03_11-37-19](https://user-images.githubusercontent.com/42062385/43636169-9e609ab0-9711-11e8-838b-e9337fb6df4f.png)

I have attached above examples of my data being wonky, and other people's working fine at that time. The same data is displayed inside act too so it's not the overlay. I have also attached proof of the developer of the overlay stating that he has the same exact problem.

**Comment by ravahn** [comment]
I still haven't been able to fix this, but it looks suspiciously like the same thing that is happening in #212 . I'm going to link these two issues, but close this one.  I don't have a solution yet, but do have a theory - and the latest 2.0 version of the FFXIV Plugin may have resolve the problem already, but I haven't confirmed it yet.
