### ISSUE TITLE
Monsters at very low HP display no HP bar

### ISSUE THREAD

**Issue by chordscollide** [ravahn/FFXIV_ACT_Plugin#18]
Likely due to a truncation error. The mob just stays like this:

http://puu.sh/f3DuF/9ed5e40daa.jpg

**Comment by chordscollide** [comment]
A bit more info:
This seems to a be a "very low HP" monster state, as the HP bar actually flashes in game. 

An idea would be to have the overlay's HP bar visible until the combatant removed or another target is selected.

**Comment by ravahn** [comment]
Took a long time to track this down, turned out that there was a failsafe when calling windows GDI to not send a draw width of zero.  It's fixed in 1.4.0.1 (to be released soon).
