### ISSUE TITLE
Chat logging doesn't contain character name

### ISSUE THREAD

**Issue by bmwang** [ravahn/FFXIV_ACT_Plugin#181]
Hi! I'm not actually sure if this is an issue here, on ACT, or a misunderstanding/misconfiguration on my part, but I'm wondering if anyone could shed some light on my issue.

I was trying to write an ACT plugin that reads my chat. I'm doing this by:
```
ActGlobals.oFormActMain.OnLogLineRead += OFormActMain_OnLogLineRead;
...
private void OFormActMain_OnLogLineRead(bool isImport, LogLineEventArgs logInfo)
{...}
```

However, when I see a chat line, I don't see the name of the player who sent it:

![unknown 7](https://user-images.githubusercontent.com/868700/44624940-29470c80-a8b1-11e8-93e7-b9e1e5946bf0.png)

When I take a look at the logs, though, I do see the character name (with some extra text around it):

```
00|2018-08-22T02:32:54.0000000-07:00|001b|O'�Sirius SilverwindSirius Silverwind'��|wait till i get my blm glam|d6e9e33dd46423ddb6a7d97bcc68684a
```

I've found that this also affects triggers; If I make a trigger for any mentions of my character name, only combat actions and chat messages that mention my name will activate the trigger, where I would expect any chat message I send to activate the trigger.

Is there a way to access the character name for these chat messages? Thanks!

**Comment by ravahn** [comment]
This will be in the next release of the plugin.  Here is an example of how it will look:
[10:24:20.000] 00:000a:Ravahn:Some echo text that I wrote
