### ISSUE TITLE
Broken by patch 4.4.

### ISSUE THREAD

**Issue by Manabender** [ravahn/FFXIV_ACT_Plugin#182]
I hate to be "that guy", but all FFXIV functionality has been broken by patch 4.4 (at least, so I would assume; it was working fine before, and now it does nothing).

And I REALLY hate to be "that guy", but I'm curious how long these fixes generally take. I've gotten to the point where ACT is vital to my gameplay, and I want it back. (If anything, take that as a compliment)

**Comment by woodyrob** [comment]
is that beacuse of the patch 4.4?
I cant use it either
but I am first time to use ACT.   I thought it is my problem lol.

**Comment by DAOWAce** [comment]
Same here; loaded it up to run cactbot to remind myself how a fight works (just came back after a few months).  It's not recording any data at all.

It sees the zone we're in.. but that's it.  No new entries or anything, just blank.

I don't recall it breaking for 4.3.. or I started using it after 4.3.. maybe it's just been too long for me to actually remember; but it survives minor patches, I know that!

**Comment by jas612** [comment]
It happens almost every patch @DAOWAce .

Sometimes, @ravahn beats us to it and opens his own Github issue.  More often, one or more people beat him to the punch and panic.

All in time and if @ravahn finds himself lacking time, a fork certainly will do so.  Patch-to-patch I think, for the uninitiated, is just finding the beginning memory address where the data moved to, and rarely does the format of said data in memory change.

**Comment by szalkerous** [comment]
Not sure if Ravahn needs or wants any assistance with updates, but I'll toss my offer in the ring as a professional software engineer if he wants teammates. My job is flexible with my working hours, so I could potentially get on this stuff early. :)

**Comment by jas612** [comment]
aaand I didn't check if source was on here haha @szalkerous gg

**Comment by Manabender** [comment]
If the source code isn't public, then why are there thirty forks? Surely those had to come publicly-copied source code...right? Or maybe I just don't understand how gits work.

On a totally different subject: Am I correct in assuming that, once the plugin is updated, ACT will automatically grab the new version when it's launched?

**Comment by ravahn** [comment]
Hi All, was driving today - bad timing for the patch, but unavoidable.  I'll be updating it.   Just getting started now.  Aiming for release tomorrow afternoon.

Source is closed for now, however the binary isn't obfuscated.  This is both a good thing (people can inspect the code if they are curious to make sure it is safe) and a bad thing (a few people have posted the source code without disclaimers/etc, potentially creating false branches, confusion, or hacked copies).  But it does allow someone who is interested in helping to identify changed memory signatures and updated struct offsets.  I welcome the help, but caution that it's quite complex to get it updated for both dx9 and dx11, and network parsing vs memory-only parsing.  I do it myself, while also keeping an eye out to other groups on Discord and the updated offsets they find.

**Comment by szalkerous** [comment]
> Source is closed for now, however the binary isn't obfuscated. This is both a good thing (people can inspect the code if they are curious to make sure it is safe) and a bad thing (a few people have posted the source code without disclaimers/etc, potentially creating false branches, confusion, or hacked copies). But it does allow someone who is interested in helping to identify changed memory signatures and updated struct offsets. I welcome the help, but caution that it's quite complex to get it updated for both dx9 and dx11, and network parsing vs memory-only parsing. I do it myself, while also keeping an eye out to other groups on Discord and the updated offsets they find.

Totally understandable. I have a large "secret" project that I've been working on for XIV, partially utilizing ACT as an optional info pathway, but mostly a fully DX-compliant overlay system that mocks the UI of the system and allows direct access to external resources and such. I couldn't imagine trying to explain all the nuances of that code to someone, haha. :) I'm just getting tired of having to tab out for things like websites and youtube videos, and I want it to look as natural as possible... so a homemade DX GUI was the path I took. However some of the things, like URL detection, need a parser to work since I'm not about to reinvent _that_ wheel. I digress.

Knowing it's un-obfuscated I suppose I could go that route, but I generally wouldn't do so unless the author permitted it, since I would hate for people to do that to mine. I'll keep that in mind for the future.

**Comment by Squall-Leonhart** [comment]
its only not working in the additional zones.

**Comment by DAOWAce** [comment]
Thank you for the update!

**Comment by Adminjojo** [comment]
Thank you for the update :)
