### ISSUE TITLE
logs with a leading "1F :"

### ISSUE THREAD

**Issue by neko8** [ravahn/FFXIV_ACT_Plugin#187]
Thank you so much for updating the plugin. 

May I ask you a favor?
Please add 1F (gauge) data dump back to the log.

**Comment by gaogaostegosaurus** [comment]
Just wanted to second this. I have some triggers that use this data to read gauge (didn't know it was something that was only recently made available... haha).

**Comment by gaogaostegosaurus** [comment]
Any news on this? Is it something wrong with my setup or is it actually missing?

**Comment by ravahn** [comment]
These should be returning in the next version (1.7.2.6)
