### ISSUE TITLE
SkillID in MasterSwing Tags

### ISSUE THREAD

**Issue by philarr** [ravahn/FFXIV_ACT_Plugin#19]
An enhancement request to include the SkillID in the MasterSwing tags. Currently some attacks done by boss like Kaliya or Bahamut Prime will show Japanese characters or other unicodes like Greek Alpha/Beta. It will be easier to map spell information by ID than by name as well because some spells share the same name but different ID!

**Comment by ravahn** [comment]
Sure, I'll add this.  I'll also add Buff IDs to the MasterSwing tags.  Should be in the next update.

**Comment by ravahn** [comment]
This has been completed in v1.3.0.16.
