### ISSUE TITLE
O11 Parsing with Jammer

### ISSUE THREAD

**Issue by megaoka** [ravahn/FFXIV_ACT_Plugin#194]
Parsing is messed up on O11, as it parses the Jammer usage. I'm just filtering it, but if you don't it parses it.

Not my photo, but a good example:
https://external-preview.redd.it/TiGajrJci6qN8ljkH4F_j65OS_wuN7Oi4s3ZpOAz2kM.png?s=48c5eb12df60399005a587fd027183be2532152a

**Comment by ravahn** [comment]
I believe this was fixed a while back.  I modified Omega Jammer as applying to a new / fake combatant called Omega Jammer.
