### ISSUE TITLE
EQ2 Flames Link is Spam

### ISSUE THREAD

**Issue by Fireye00** [ravahn/FFXIV_ACT_Plugin#196]
While looking for the changelog, I mistakenly clicked on the discussion link in the README.md.  It looks like EQ2 Flames forum link (http://www.eq2flames.com/plugin-discussion/98088-ffxiv-arr-plugin.html) is no longer valid, and redirects to a spam domain.  Can you update the readme with an appropriate link, or remove it?

**Comment by ravahn** [comment]
Good catch, I removed it.  ACT now has its own forum site, but I'm not active there.  Best way to contact me is vial email to ravahn (at) hotmail.com.
