### ISSUE TITLE
Patch 4.5

### ISSUE THREAD

**Issue by Borokar** [ravahn/FFXIV_ACT_Plugin#197]
Broken with the newest Patch 4.5 is that correct? or did i destroy something.
Shows me the Place where i am but is not parsing anymore and i dont see an HP Bar.
Firewall and Admin things are correct it worked yesterday so i think it could be today because of the 4.5 patch.

Sorry if i am stupid

greetings

**Comment by Lifell** [comment]
You're right Borokar. Doesn't work for me either.

This is my log in the Plugins > FFXIV Settings tab: https://pastebin.com/y79HAbxe

**Comment by nazgulsenpai** [comment]
Please read the last release on https://github.com/ravahn/FFXIV_ACT_Plugin/releases

"A note about the upcoming 4.5 FFXIV update: I will be travelling on Jan 8th and will probably not be able update the plugin until Jan 9th or 10th. Most likely DX11 network mode will be release first, and the rest may have to wait a while."

**Comment by DAOWAce** [comment]
It always breaks every single major patch.

Nothing to do but wait for the author (or someone else knowledgeable) to update it.

**Comment by nazgulsenpai** [comment]
It's a closed source project. Only the developer can update it.

**Comment by DAOWAce** [comment]
And here I thought all github projects were open source.  TIL.

**Comment by nazgulsenpai** [comment]
Same, i even opened an issue asking where the source was a while ago :3

**Comment by R-eenignE** [comment]
I mean, he does say it in the readme that this is only really an issue tracker :P

`This project is to track releases and issues for the ACT FFXIV Plugin. The source code is not currently public.`

**Comment by PommeVerte** [comment]
@ravahn Would making pull requests against machina FFXIV with updated headers be of any help? I'm assuming you use that for the plugin?

**Comment by R-eenignE** [comment]
@Akurosia do you use the special spell timers plugin? Try disabling it and seeing if that makes a difference. I recall reading that plugin was causing an issue like that.
