### ISSUE TITLE
ACT under-reporting tick damage for SAM's Higanbana

### ISSUE THREAD

**Issue by mysaltydog** [ravahn/FFXIV_ACT_Plugin#198]
Hello, I noticed a consistent and rather substantial discrepancy in ACT's reporting of DoT damage ticks for SAM's Higanbana compared to what is displayed in game.  Not sure if the Kaiten buff is being incorrectly simulated, DoT potency is incorrect, or what not.  In a duty instance, ACT reported several of my ticks being as low as 717 damage.  I went to test it out on a dummy and when looking at the numbers in-game, none of the ticks were below ~1130.  I check the log for the duty instance and all of the applications of Higanbana were properly buffed by Kaiten.

Here are some numbers I've copied down from hitting a dummy.  Left column is in-game ticks, right column is what ACT is simulating:

1146　—　1170
1133　—　1501
1245　—　936
1457　—　1170
1536　—　936
1483　—　936
1250　—　936
1897　—　1876
1868　—　936
1535　—　1876
1228　—　936
1175　—　1501
1441　—　936
1139　—　1170
1246　—　1876
1936　—　1501
1550　—　1170
1417　—　936
1145　—　1170
1250　—　1501

1146　—　1501
1152　—　1170
1415　—　1501
1221　—　1170
1213　—　1170
1547　—　936
1533　—　1501
1517　—　1501
1875　—　936
1470　—　1501
1937　—　1876
1245　—　1170
1963　—　1876
1923　—　936
1488　—　1170
1135　—　1170
1174　—　936
2450　—　1876
1246　—　1170
1157　—　1170

1222　—　936
1200　—　936
1550　—　1170
1161　—　936
1153　—　1876
1152　—　936
1990　—　936
1476　—　1170
1952　—　1876
1968　—　1170
1427　—　1501
1863　—　1501
1245　—　936
1537　—　936
1195　—　936
1492　—　936
1161　—　936
1158　—　936
1452　—　936
1152　—　1501

2463　—　1501
1156　—　1170
1987　—　936
1185　—　936
1186　—　936
2358　—　1170
1224　—　936
1515　—　936
1234　—　1170
1435　—　936
1172　—　1876
1220　—　936
1148　—　936
1462　—　1501
1530　—　1170
1899　—　1501
1237　—　936
1251　—　936
1137　—　1501
1214　—　1170

In-game averages:
~1203 normal damage
~1533 direct hit
~1927 critical hit
~2423 direct critical hit

ACT-simulated numbers:
936 normal damage
1170 direct hit
1501 critical hit
1876 direct critical hit

Differences:
~267 normal damage (ACT simulation is ~77.8% of in-game ticks)
~363 direct hit (ACT simulation is ~76.3% of in-game ticks)
~426 critical hit (ACT simulation is ~77.9% of in-game ticks)
~547 direct critical hit (ACT simulation is ~77.4% of in-game ticks)

It looks like ACT is under-reporting by about 22~24% based on a sample size of 80 ticks.  To be sure, this is not an issue of proc rates of direct and critical hits, but of the damage of the ticks themselves.  I have no clear idea of what goes on under the plug-in's hood, but it seems like either Kaiten's %  increase is configured to +25% instead of +50% in relation to DoT ticks, or the DoT potency is configured to a lower value.  Not really sure what was going on with ACT during the aforementioned instance run since all applications of Higanbana were buffed by Kaiten, so the reporting of minimum ticks of 717 tells me there's something weird going on with the plug-in.

**Comment by mysaltydog** [comment]
Hi there!  I will send the log file shortly.

Yes, Kaiten does in fact apply to all aspects of Higanbana's damage, both direct and DoT.  Using a unbuffed Higanbana will yield DoT ticks that are significantly weaker than when buffed with Kaiten.

**Comment by ravahn** [comment]
The next update - v1.7.2.6 - will have a fix for this, so that Kaiten is applied to the Higanbana dot ticks when it is up.  Thanks for the sample logs, they were helpful!

**Comment by mysaltydog** [comment]
Thanks a bunch for looking into it!  I'm also wondering if this will also fix the problem where, while in duty instances, the influence of Jinpu and damage variance on Higanbana ticks are also unaccounted for (in simulated dots, at least)?  I wrote you a follow-up email in regards to it but not sure if it got your attention.
