### ISSUE TITLE
Feature Request: Show combatant server

### ISSUE THREAD

**Issue by chadouming** [ravahn/FFXIV_ACT_Plugin#199]
Hey, since they now append server name to the player name, would it be possible to add player's server name to the playerData structure ? It would be possible to do through my plugin though if i can avoid to parse all line from the logs it would be best. Since you're already doing it i don't think it would add much overhead to your plugin.

It would be much appreciated!

**Comment by ravahn** [comment]
Not sure what the playerData structure is, but I've added it to the Combatant structure in memory, and it is also in the log data as of the last release (1.7.2.5).  Next version will included it in the encounter text inside ACT in a more readable manner as well.

It won't currently include the server name as part of the player name when rendering encounters, overlays, etc.  That may get added in the future as an option, but won't be in the next few weeks.
