### ISSUE TITLE
Any news about dx9 ?

### ISSUE THREAD

**Issue by Meelyyy** [ravahn/FFXIV_ACT_Plugin#200]
It's been more than 2weeks and we'd love to know how is the update cuz some of my friends can't analyse their logs due to no update to dx9 ~ we appreciate your hardwork ♡

**Comment by ravahn** [comment]
Will be soon, did most of the updates for DX9 today and just need to finish some misc cleanup and final testing tomorrow, hopefully.

**Comment by Meelyyy** [comment]
FeelsGoodMan
