### ISSUE TITLE
Adding BLU

### ISSUE THREAD

**Issue by WadeWilsonWannabe** [ravahn/FFXIV_ACT_Plugin#201]
Any news on when Blue Mage will be added to the parsing? I figure it would follow the pattern for new classes and be Blu = 36, //0x24

**Comment by ravahn** [comment]
This will go out soon, sorry for the delay.

**Comment by WadeWilsonWannabe** [comment]
Awesome. I appreciate the update. I know you are busy and (probably) have a day job as well as a life beyond this project. Any help I can provide, now or in the future, please let me know.
