### ISSUE TITLE
Damage numbers drastically lower in ACT vs. in-game #32

### ISSUE THREAD

**Issue by NikolasCalypso** [ravahn/FFXIV_ACT_Plugin#202]
I have the same problem as issue #32 which was closed (but I don't see any resolution to it). I've made a few posts on different sites hoping someone could help, but as it has already been posted here, I guess this is the best place.

Plugin version  1.7.2.5
Logs: Attached

---

Heya, I'm just setting this up for the first time, so maybe I did something wrong. I followed the guides and everything seems okay, except the parser seems to be missing a lot of damage.

For example I fought a nearby Gazelle Hawk with my Warrior. I hit for 2,697 damage but ACT shows 180-190 damage.

So for a target that apparently has 40k HP, I killed it with only 4,316 damage total!

I'd really appreciate if anybody could help with this. 

Thanks in advance.

*EDIT* As a point of clarification, ACT isn't failing to record my actions, it records the wrong results (low numbers) of my actions
[Network_20190125.log](https://github.com/ravahn/FFXIV_ACT_Plugin/files/2797876/Network_20190125.log)

**Comment by ben1488garrison** [comment]
[Plugins]>[FFXIV Settings]>"Parse Options" frame; see if the last checkbox has "Parse Potency Amounts" enabled.
![imagen](https://user-images.githubusercontent.com/19628590/51781700-26b83f80-20fb-11e9-8b22-dc0f7911562a.png)

**Comment by NikolasCalypso** [comment]
Turned that up (set my settings the same as your screenshot) and it looks much better. Thanks a ton.
