### ISSUE TITLE
Dx9?

### ISSUE THREAD

**Issue by Meelyyy** [ravahn/FFXIV_ACT_Plugin#205]
Still no update yet?

**Comment by nazgulsenpai** [comment]
This isn't my project but I'd assume it has something to do with most players using the DX11 client in addition to Square Enix dropping support for DX9 starting in 5.0.

https://na.finalfantasyxiv.com/lodestone/news/detail/46f28ce6bd697e3fd08e0e70c3c7646e5f5a3385

The way forward is to upgrade to DX11.

**Comment by ravahn** [comment]
DX9 should be working as of a few months ago.
