### ISSUE TITLE
Failed: Cannot detect one or more FFXIV memory signatures

### ISSUE THREAD

**Issue by haasn** [ravahn/FFXIV_ACT_Plugin#206]
- **Game version:** 2019.01.18.0001.0000 (3784682)
- **Plugin version:** 1.7.2.5
- **ACT version:** 3.3.3 r258
- **OS version:** Windows 10.0.16299 Build 16299

This happens regardless of the scanning mode. I am running ACT as administrator. I have the windows firewall disabled. Clean install of ACT, no settings changed. I tried starting ACT after FFXIV and vice versa. I am running FFXIV in DX11 mode.

Was there a new patch very recently, or something?

### Full log
```
Error: empty signature for [Target].
ERROR: Unable to find Signature for [Target].
Error: empty signature for [ChatLog].
ERROR: Unable to find Signature for [ChatLog].
Error: empty signature for [MobArray].
ERROR: Unable to find Signature for [MobArray].
Error: empty signature for [ZoneID].
ERROR: Unable to find Signature for [ZoneID].
Error: empty signature for [ServerTime].
ERROR: Unable to find Signature for [ServerTime].
Error: empty signature for [PartyList].
ERROR: Unable to find Signature for [PartyList].
Error: empty signature for [Player].
ERROR: Unable to find Signature for [Player].
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [Target]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ZoneID]
Error: Unable to read signature [Target]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [Target]
Error: Unable to read signature [Target]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ZoneID]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [Target]
Error: Unable to read signature [Target]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ZoneID]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [Target]
Error: Unable to read signature [Target]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ZoneID]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [Target]
Error: Unable to read signature [Target]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ZoneID]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [Target]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ZoneID]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [Target]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [Target]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ZoneID]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [Target]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [Target]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ZoneID]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [Target]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [Target]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [MobArray]
```

**Comment by haasn** [comment]
In case it helps, this is the sha256sum of my game executable:

```
30c91381e70b825d6038c86ad4a8c33497b8e922f294706f511c064681e15d71  ffxiv_dx11.exe
```

**Comment by haasn** [comment]
Seems there was a new patch today, so I guess it's not working due to that regardless, now? Also, while investigating the new patch, I noticed that there are actually two different versions of `ffxiv_dx11.exe`. One is located in the directory `trial`. I'm beginning to suspect more and more that the "free trial" version of the game client is not actually the same game client as everybody else is using, mayhaps this is the reason for why ACT was not working for me initially?

```
38a26aeae94fa727f3ed6364150361184968a748670d050176aec806270eb7ac  game/ffxiv_dx11.exe
045901ddcced3a985f7d530c29fa1427f0275a58d8dde12d3a2b5d6313d53b2f  trial/ffxiv_dx11.exe
```

**Comment by haasn** [comment]
Tried a fresh, clean install of FFXIV (after today's patch). Still doesn't work. Anyway I can debug this? Can you release the source code to me, so I can solve this problem myself? (Under NDA if you'd prefer)

**Comment by haasn** [comment]
Nope, tried upgrading to the Starter Edition, and the process running is definitely `game/ffxiv_dx11.exe`. Still doesn't work.

**Comment by haasn** [comment]
Okay, I think I found the error. It's part of this logic:
```csharp
				if (_config.Process.ProcessName == "ffxiv")
				{
					_config.ClientMode = FFXIVClientMode.FFXIV_32;
				}
				else if (_config.Process.ProcessName == "ffxiv_dx11")
				{
					_config.ClientMode = FFXIVClientMode.FFXIV_64;
				}
				else
				{
					_config.ClientMode = FFXIVClientMode.Unknown;
				}
```

On my machine, for some reason, the ProcessName of the FFXIV process is in all-caps (the ProcessName is "FFXIV_DX11"), which the `Process.`GetProcessByName` function finds (since it's apparently case-independent), but your code maps this to `FFXIVClientMode.Unknown`. Solution, and a few suggestions:

1. Make these checks case-insensitive
2. Log an error and return false in the Unknown case

**Comment by haasn** [comment]
> The executable location is on a network share (zfs, mounted via smbfs from a linux host), which might affect the process name somehow

Turns out this was the issue. I moved the game executables over to the local disk (keeping the data files on a network share by using a symlink), and now it's all lowercase instead of all uppercase.

I'll leave this issue open, since it's still a legitimate issue to fix. Anyway, I hope you would like to officially release the source code in the future. Having to reverse engineer my way through the dll is a needless burden to solving problems. :-)

**Comment by WadeWilsonWannabe** [comment]
Not to mention being able to test potential fixes and/or speedy bug fixes. I was able to reverse engineer it to see the code as well, but would love to be able to build and test on my local machine. More than willing to sign an NDA and submit any code changes that go live to Ravahn. I am sure he has a day job and a life, and doesn't have all the time in the world to maintain this project as much as he would like.

**Comment by haasn** [comment]
Fixed in the latest release. Thanks!
