### ISSUE TITLE
ACT not parsing (1.7.2.6 and 1.7.2.8)

### ISSUE THREAD

**Issue by redeven** [ravahn/FFXIV_ACT_Plugin#209]
Hello! I've been trying to update to the two latest versions and once I do, the parsing doesn't work. 

It only starts working again when I downgrade to 1.7.2.5.

**Comment by Squall-Leonhart** [comment]
ERROR:    at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
ERROR:    at Machina.RawSocket.CreateRawSocket(UInt32 localAddress, UInt32 remoteAddress)
ERROR:    at Machina.RawSocket.Create(UInt32 localAddress, UInt32 remoteAddress)
ERROR:    at Machina.TCPNetworkMonitor.UpdateSockets()
ERROR: Invalid Line type    at Machina.TCPNetworkMonitor.Run(Object state)|fd091d49ef84bdfa2eaabe9374d2c18f

**Comment by Dotpeach** [comment]
Same issue here, and I still have no idea how to fix it :/
