### ISSUE TITLE
Summoner dps always abit off

### ISSUE THREAD

**Issue by lyra133** [ravahn/FFXIV_ACT_Plugin#210]
Hello,

I noticed that ACT shows different DPS numbers then FFlogs does after I upload the logfile. Its always 250-300 lower then it should be(what fflogs calculates) and it only applies to summoner as far as I can tell - didn't test all the different jobs, but it looked fine for drg, nin, sam, war, pld, sch and ast. Only the dps value of the smn were always off.

**Comment by ravahn** [comment]
The difference between FFLogs and ACT DoT simulation has been around for a long time.  I did a pass for improving ACT DoTs at the end of 2018, and it should be more accurate.

I do want to point out that you are making an assumption that FFLogs is providing accurate DoT attribution to different players, but this may or may not be correct.  The ACT Plugin still has some room for improvement, but so does FFLogs.  I'll check in with some summoners I know to do some additional testing on this, but I will not have time to address anything other than simple bugs until after the expansion release (summer).
