### ISSUE TITLE
Track buffs provided by Logos actions for DoT estimation

### ISSUE THREAD

**Issue by haasn** [ravahn/FFXIV_ACT_Plugin#214]
I've compiled a list of buffs provided by eureka logos actions and the damage increases they provide:

```
Buff ID (decimal) - Buff name - Effect
1656 - Boost - 30% to next weaponskill per stack (does not affect abilities even if they are physical, it's similar to samurai Kaiten)
1652 - Magic Burst L - 100% "spell damage"
1646 - Bravery L - 10% all damage
1653 - Double Edge L - 15% physical damage per stack
1631 - Wisdom Of The Aetherweaver - 60% magic damage
1632 - Wisdom Of The Martialist - 40% all damage
1636 - Wisdom Of The Skirmisher - 20% all damage
1637 - Wisdom Of The Watcher - -5% all damage (yes, negative)
1638 - Wisdom Of The Templar - -5% all damage
1639 - Wisdom Of The Irregular - 30% all damage
1739 - Wisdom Of The Elder - 35% magic damage
1740 - Wisdom Of The Duelist - 40% physical damage
1741 - Wisdom Of The Fiendhunter - 25% physical damage
```

I had a look through the buff list xml but I'm not quite sure how to place these, since they affect all jobs. (Unless we want to go through each job and only include the relevant buffs for that job?) I'm also not sure how to properly code things like Boost or Double Edge L which apply a cumulative bonus per stack.

If you could give me a simple example of how to code one of these properly, I could go through the rest.

Also, there are some debuffs which are relevant for enemies:
```
1654 - Spirit Dart L - 8% all damage
1655 - Banish L - 25% all damage
```

**Comment by haasn** [comment]
Also, in terms of importance, the only four that would really be relevant to fix are the first four, specifically `Boost`, `Magic Burst L` and `Double Edge L`. (Bravery L is also nice but it lasts 5 minutes and only provides 10%, so the error will be marginal)

**Comment by ravahn** [comment]
I'm taking a stab at this, although from sample logs, the client buff limit may be causing some issues here.  Will be included in the next update.

**Comment by ravahn** [comment]
This went out with one of the pre-5.0 update  - how does it look? I am sure it can use improvement, but did it help?

**Comment by haasn** [comment]
Oh, yes! It worked wonderfully for the purpose I needed it for. Feel free to close.
