### ISSUE TITLE
Add log lines for tethers

### ISSUE THREAD

**Issue by quisquous** [ravahn/FFXIV_ACT_Plugin#215]
This should be very similar to add as the 0x1B head marker log lines.  It's also an 0x0142 ActorControl message, but instead of its type being 0x22, the type is instead 0x23.  The headmarker type is stored in the first uint32 param, but for tethers it's the second, with the target id being in the third uint32 after the type.

See: https://gist.github.com/quisquous/6e7077f3d69d29a808ab76a9de9953e9

Having log lines for tether messages would be a huge improvement for future triggers.

**Comment by ravahn** [comment]
Adding this to the next update, pending some testing.

**Comment by ravahn** [comment]
This should be added now, let me know if you see it working.

**Comment by quisquous** [comment]
It's been great, thanks!

e.g. https://www.twitch.tv/videos/442060800?t=45s
e.g. https://www.twitch.tv/videos/444831551?t=6m13s
