### ISSUE TITLE
FFXIV_ACT plugin error

### ISSUE THREAD

**Issue by retsu3** [ravahn/FFXIV_ACT_Plugin#217]
So, just today I started getting a weird error that I've never seen before any other time I used ACT. The program itself works just fine, but when I try to enable the FFXIV plugin itself. This error message pops up http://prntscr.com/o6ghyv

To me, that's all gibberish, but I'm not sure if I was the only one this was affecting or if there was another issue that I should be aware of with my plugin/program.

**Comment by ravahn** [comment]
I'm not sure what the cause is, but recently I've heard that some of the additional ACT plugins can interfere.  Try disabling all of them, restart ACT, and enable the FFXIV Plugin.

Also try using the newest version (2.0.2.1), and see if that helps.
