### ISSUE TITLE
32 Bit process cannot access modules of a 64 bit process ACT Issue

### ISSUE THREAD

**Issue by Kusaka777** [ravahn/FFXIV_ACT_Plugin#218]
32 Bit process cannot access modules of a 64 bit process ACT Issue? Plugin crashing and not working and ive tried reinstalling couple times to no avail. Idk how to fix it and also posted on reddit for answers with no luck either.

**Comment by kyager** [comment]
You're trying to use the 32bit version on a 64bit system, it won't work, use the other client (not the 32bit version, should be in the same install folder).

**Comment by Kusaka777** [comment]
It isnt tho. Apparently it is only 32 Bit version, and when you reset it up it just keeps using the 32bit. And i cannot find just a flat out 64bit version download anywhere. If you know somewhere I could, lmk. Ty

**Comment by ngld** [comment]
If you got ACT from the [official website](https://advancedcombattracker.com/download.php), it should have two executables in its program directory: `ACTx86.exe` and `Advanced Combat Tracker.exe`.
Always use the second executable. If that still doesn't work, you probably need to update (or fix?) your .NET Framework.

**Comment by Kusaka777** [comment]
Ok ill try this, as well. ty

**Comment by Kusaka777** [comment]
Thanks ngld, i had to fix the .NET stuff. Thanks guys, much appreciated!!
