### ISSUE TITLE
5.0 Update: Cannot detect one or more FFXIV memory signatures, please exit FFXIV and try again.

### ISSUE THREAD

**Issue by FeiiMiyu** [ravahn/FFXIV_ACT_Plugin#219]
5.0 Shadowbringers error:

Failed: Cannot detect one or more FFXIV memory signatures, please exit FFXIV and try again.

ERROR: Unable to find Signature for [ServerTime].
Error: Unable to read signature [ServerTime]
ERROR: Error with chat log - Log length array is too small., STACK=   at FFXIV_ACT_Plugin.Memory.ScanLogBuffer.ParameterizedRun(Object parameter)
ERROR: Error with chat log - Log length array is too small., STACK=   at FFXIV_ACT_Plugin.Memory.ScanLogBuffer.ParameterizedRun(Object parameter)
Error: Unable to read signature [ServerTime]

**Comment by sethzin** [comment]
Same issue since update

**Comment by Zurrar** [comment]
Same issue, started after update

**Comment by tyweezy15** [comment]
Same issue here also, any updates?

**Comment by yorushika** [comment]
Same here.

**Comment by ShammyLevva** [comment]
Give the developer a break the games only been up a few hours and they've not had time to test. What you should be doing is click debug and creating a network log file to upload so they have some data. 

[This is one small test sample data file](https://www.dropbox.com/s/j3qk6mfqimn2qia/Network_20190629.log?dl=0) hope it helps identify issue.

**Comment by FeiiMiyu** [comment]
I'm not upset, just bringing up an issue so others don't think it's just them. Check the Discord for an updated ACT. Good luck everyone.

**Comment by galaxy119** [comment]
I'd be able to help, if there was actual source code for the plugin anywhere :roll_eyes:

**Comment by ShammyLevva** [comment]
> I'd be able to help, if there was actual source code for the plugin anywhere 🙄

You mean like the source that's available by clicking the <> code tab at the top of this page?

**Comment by ngld** [comment]
That only contains zips of the compiled DLL not the actual source.
However, the actual network parser is open source (https://github.com/ravahn/machina) and dnSpy is a thing.

**Comment by haasn** [comment]
You can also decompile the FFXIV ACT plugin using [dnSpy](https://github.com/0xd4d/dnSpy). That's what I do when I want to poke around in its source for stuff like this. ^^

**Comment by galaxy119** [comment]
dnSpy != source code

There's alot you can do with dnSpy, granted, but it's 1000x easier with source. Plus I'd be able to poke around and adapt the network parsing to work on Linux since that's my main OS.

**Comment by sethzin** [comment]
No one said they are upset or anything. They are just reporting a bug. you know, what this page is for? :)

**Comment by ravahn** [comment]
The plugin has been updated to support 5.0.  It will go out to the ACT updater shortly, but has been posted to discord and github.

**Comment by haasn** [comment]
Thank you so much for your continued work on this amazing plugin, @ravahn. The community as a whole is deeply grateful for your efforts. \o/
