### ISSUE TITLE
Cancelled Spells Affecting MinHit, Average, etc

### ISSUE THREAD

**Issue by dannyrscott** [ravahn/FFXIV_ACT_Plugin#22]
Not sure if this is an issue with this plugin or ACT itself but here goes.

When a spell is cancelled (you start to cast the spell and then move or jump or whatever), it is logged as a hit for no damage with a flag of cancelled.

These spells are still recorded as "hits" for the purposes for number of the spell cast, minhit of the spell, average, etc, etc.

**Comment by ravahn** [comment]
This should be fixed in the next release, v1.7.2.6.  I changed cancelled swings from reporting as "No Damage" to instead report as "Unknown Damage" to ACT.  Unfortunately this does appear to affect the 'To Hit' columns, but does not report as a miss.
