### ISSUE TITLE
Overlay freezes when act in minimized to tray

### ISSUE THREAD

**Issue by OnyxMemory** [ravahn/FFXIV_ACT_Plugin#220]
If I ever minimize ACT to the system tray, the entire overlay will freeze and not update until I open the window again. I only started having this issue now.

I've trying doing a completely fresh install but it hasn't fixed it.

For example here, I'm not targeting anything but the overlay is still showing:
![image](https://user-images.githubusercontent.com/43679188/60399631-8b514d80-9b24-11e9-9620-299a5a6d06da.png)

If I open the window again or minimize it to the taskbar, it will disappear, update, act normal as it should.

**Comment by ravahn** [comment]
That is very odd.  I wonder if minimizing ACT is freezing its UI thread.  

Does the built-in mini-parse overlay continue to update?

**Comment by OnyxMemory** [comment]
Yes the mini-parse/overlayplugin.dll seems to be working fine, the hp overlay is the only thing that seems to be having that issue.

**Comment by ravahn** [comment]
Found the culprit.  I changed the overlay update thread to check oFormACTMain.Visible = true, which will not be the case if ACT is minimized to the tray.    This will be fixed in the next release.
