### ISSUE TITLE
Automaton Queen not being merged with owner when "Combine Pets with Owner" is checked

### ISSUE THREAD

**Issue by jchrisrogers** [ravahn/FFXIV_ACT_Plugin#221]
Automaton Queen is being tracked as it's own separate entity. It looks like Automaton Queen is actually showing up as a companion rather than a pet.
![image](https://user-images.githubusercontent.com/19679596/60401569-3f64cf80-9b49-11e9-92e6-6050a8170c0f.png)

Here are some log entries, if it helps:

`00|2019-06-30T14:56:15.0000000-05:00|0aa9||   The striking dummy takes 13075(+75%) damage.|3b98028e596994eb828482f7c0865520
21|2019-06-30T14:56:16.1970000-05:00|106F9CC4|Cerila Jawantir|4075|Automaton Queen|106F9CC4|Cerila Jawantir|33|120000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|77108|77108|10000|10000|0|1000|708.9971|27.1531|284.8765|77108|77108|10000|10000|0|1000|708.9971|27.1531|284.8765||41376fe8018896829480954c4ee84f28
00|2019-06-30T14:56:15.0000000-05:00|082b||You use Automaton Queen.|7a0c6bae443359028ef1b2d6e49ca393
03|2019-06-30T14:56:16.2860000-05:00|104cea45|Ero Mori|23|46|934e|2710|0|37|Lamia|0|0|346.3149|51.02089|346.3149|d9838887623702f7912d6c26244dcf22
03|2019-06-30T14:56:16.2860000-05:00|4001b6a3|Automaton Queen|0|50|12c84|2710|106f9cc4|0||8230|10490|286.5111|27.11646|286.5111|b59d0ac7d1407c8e46c9e0950680fb80
31|2019-06-30T14:56:16.5860000-05:00|106F9CC4|CA00001F|32002D30|12961902|7FAD|38591791fef8e15402c5133dce51f101
21|2019-06-30T14:56:17.6000000-05:00|106F9CC4|Cerila Jawantir|08|Shot|400004B4|Striking Dummy|720003|9C80000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|2505162|2862500|0|0|0|1000|718.0651|26.95955|285.0142|77108|77108|10000|10000|0|1000|708.9971|27.1531|284.8765||16928da493e0a89d19b8c73ec31b085f
34|2019-06-30T14:56:17.6100000-05:00|4001B6A3|Automaton Queen|4001B6A3|Automaton Queen|01|91d7bdae10a22c0a079ec4609efb901b
00|2019-06-30T14:56:17.0000000-05:00|0aa9||You hit the striking dummy for 2504 damage.|184a6116c80dacbd8be2981a1e034d42
`

**Comment by ravahn** [comment]
Thanks, I was missing a number of different pets, and it was worse with non-english language settings.  Version 2.0.2.2, just released, should fix this.
