### ISSUE TITLE
Overlay not showing parses? (version 2.0.2.3)

### ISSUE THREAD

**Issue by shiraiseyuki** [ravahn/FFXIV_ACT_Plugin#224]
I just downloaded the new update of the plugin. It does parse, but it is not showing on the overlay.
it only shows the time of fight, and the tab (name, D%, DPS, CH, etc), but there is no name of the player nor the dps number.

![parse issue](https://user-images.githubusercontent.com/52551570/60691039-6725a180-9e81-11e9-9d0a-d0c1f7627acd.png)

**Comment by ravahn** [comment]
This was a temporary problem with Kagerou itself, related to an incompatibility with OverlayPlugin.  it was fixed shortly after by the author, and work is being coordinated by others in the FFXIV Plugin discord to upgrade OverlayPlugin itself.
