### ISSUE TITLE
The need for a cross-version support of LOGS logged by plugin

### ISSUE THREAD

**Issue by realmcat** [ravahn/FFXIV_ACT_Plugin#225]
Would it possible to take into consideration that making a ‘translater’ which can transform FFXIVLogs recorded by plugin for example ver.2.0.2.2 into Logs recorded by ver.2.0.2.3 supported by FFlogs uploader.

**Comment by ravahn** [comment]
Unfortunately this is not something I'm going to work on.  I coordinated release of the 2.0.2.3 changes with Kihra (FFXIV Logs author), and there were some bugs in 2.0.2.3 which caused the logged data to be less accurate than later versions, so it made sense at the time both to change the log format, and to not support the earlier format.  The plan is to only change log line formats significantly around major updates - for example, when the game itself changes the packet format significantly, or major expansions are released.  It might take a few days to coordinate these changes, even after ACT appears to be working, as was the case here.
