### ISSUE TITLE
ACT not parsing accurate DPS

### ISSUE THREAD

**Issue by Flowerpriestess** [ravahn/FFXIV_ACT_Plugin#227]
Alright, I'm kind of at a loss of what to do. Before Shadowbringers, ACT was perfectly fine. I haven't changed any folders or options, yet with the arrival of Shadowbringers ACT has't been parsing correctly at all.

My opening rotation ends up looking something like this, as does the rest of the DPS in my party when I'm in instances:
![image](https://user-images.githubusercontent.com/52675081/60834309-714fe480-a18e-11e9-8b28-5e400a1e5371.png)

DPS ends up being in the double and triple digits, but nothing beyond that.

- ACT is always run as administrator
- ACT is allowed through the firewall
- Log file locations are correct
- I've attempted to manually select the process ID. It's made no difference
- Parse mode is set to network
- I've tried a clean install of ACT and the plugin thru github
- Disabled high-performance network filter to see if that would change anything. It hasn't

I'm not very tech savvy so I've been relying on searches to troubleshoot what's going on, though that's yielded me no results so far. I'd love to find out what the problem is because this is driving me nuts. Thank you in advance for any and all help I'm given ;___;

**Comment by ravahn** [comment]
Based on the DPS - 35.16 - I wonder if the "(DEBUG) Parse Potency Amounts" checkbox on the Plugins -> FFXIV Settings tab was somehow checked.   By default, all the checkboxes can be left unchecked.  If it isnt checked, I recommend joining the FFXIV Plugin discord for more troubleshooting help.
