### ISSUE TITLE
Can't get overlay to work

### ISSUE THREAD

**Issue by Doomhammer3** [ravahn/FFXIV_ACT_Plugin#228]
When I try and enable the overlay I get this message 

https://imgur.com/a/M4DU2Sl

What am i doing wrong? I followed your youtube guide.

**Comment by ravahn** [comment]
I recommend you join the Discord for overlay troubleshooting help.  I can only help with the FFXIV plugin itself.  Based on the assembly (HtmlRenderer) this is not related to the base FFXIV plugin.
