### ISSUE TITLE
Some log lines missing timestamp

### ISSUE THREAD

**Issue by quisquous** [ravahn/FFXIV_ACT_Plugin#229]
Example:
```
[05:22:58.000] 00:3b29:⇒ Aenc Thon, Lord of the Lengthsome Gait takes 10592 damage.
Player Stats: 32:3164:295:3591:188:127:310:3164:444:2251:188:127:2018:797:368:0:1108
[05:23:00.237] 19:Aenc Thon, Lord Of The Lengthsome Gait was defeated by Unknown.
```

It is just the "Player Stats" line that doesn't have a timestamp on it.  I noticed this when some code that assumed everything had a timestamp complained.

**Comment by ravahn** [comment]
This was a typo, I used "=" instead of "+=" operator, will be fixed in next release.
