### ISSUE TITLE
Feature Request: show 0x0B PartyList data in formatted logs

### ISSUE THREAD

**Issue by quisquous** [ravahn/FFXIV_ACT_Plugin#230]
It's pretty awkward right now to figure out the names of people in your party.  (For ucob, I track who gets hit by heavensfall).  It would be really helpful for me if the 0x0B wasn't blank and had the object ids and names (bonus: job ids?) for each person.

**Comment by ravahn** [comment]
I definitely can make some improvements here.

There's a couple of pieces of information: Party Size, and then a full list of all party and alliance IDs.  The log line in the file needs to stay the same, but I can change the parsed format to include the player names and even job ids or abbreviations if available.

Can you provide a suggestion for a format that would work for you to interpret - and keep in mind it will contain the entire alliance, not just the current party?

**Comment by quisquous** [comment]
I do not have a ton of experience with when this message is written.  I assume it's just once every time your party changes, and it just prints out the full party/alliance? And once when zoning?  Do you get a new one when somebody changes job while in a party and the icon changes?

When you say "it will contain the entire alliance", is it possible to differentiate who is in the party vs in the alliance?

What about something along the lines of:
```
0B:party size:player id1:player id2:player id3:etc
XX:player id:player name:world id:player job id:anything else (new message type, one per player in party)
```

I think this sort of thing would be the least awkward to parse.  I have some worry about having a list of lists of fields and possibly needing to add more in the future, and so having per-player informational messages seems a little bit more reasonable to me.

**Comment by ravahn** [comment]
Interesting.  I can call the following method in ACT with the additional party log lines:

Advanced_Combat_Tracker.ActGlobals.oFormActMain.ParseRawLogLine(isImport, ParsedDateTime, LogLine);

it wont appear in the file, or in the memory-based events such as ParsedLogLine, but it would be accessible via the ACT Log line events.  Let me give it a try.

**Comment by ravahn** [comment]
I spent some time working on this, but unfortunately the order of log line messages is making it difficult to extract player world/job/name.  the party log line is written before the combatant log line, so it is difficult to write separate party member log lines.  This won't make it in the next update, but I'll keep working on it.

**Comment by quisquous** [comment]
Hmm! I was thinking about this, and wanted to propose an alternative suggestion if this makes life easier for you.  Is the party list exposed from the ffxiv plugin (and enough information to look up names / worlds / jobs?  If it's not, then maybe that's an easier route?

I mean, if I really wanted this info, I could always just add memory lookups for party list myself, but it seems redundant with both what you're doing with network logs and memory signatures, and so if I can lean on the plugin I'd prefer to.

**Comment by quisquous** [comment]
Sorry, I can just use the data repository for this: https://github.com/ngld/OverlayPlugin/pull/17.
