### ISSUE TITLE
Can't disable sound

### ISSUE THREAD

**Issue by JayDeezus** [ravahn/FFXIV_ACT_Plugin#232]
I can't disable the system beep when I use "/e end" or "/e clear" from within the game client.  Sound settings in the Options tab of ACT is set to "No internal sound (Plugin or no sound)", so the plugin is generating the system beep.  There is no option within the plugin settings to disable this.

**Comment by ravahn** [comment]
Unfortunately, no, it is not part of my plugin.

I've disassembled ACT itself.  Here is the code that plays the sound:
![image](https://user-images.githubusercontent.com/6621202/61580124-3c238a80-aadc-11e9-9ffc-a649956447ab.png)

The line "SystemSounds.Asterisk.Play()" is the culprit.  Nothing I can do about this unless I replace the echo end command with my own implementation, which I don't plan to do.

**Comment by JayDeezus** [comment]
Thanks for looking into this.  I put a forum post on the ACT website referring to this issue.
