### ISSUE TITLE
Dark Knight

### ISSUE THREAD

**Issue by EnjuAihara** [ravahn/FFXIV_ACT_Plugin#233]
hi i have the problem that my shadow (lvl 80 skill ) get listed as chocobo and not combine with me

**Comment by Kaza-Shin** [comment]
II encountered this same problem with my Dark Knight (shadow) and also with my Machinist (Queen). I think it's more about summoning a pet and I wouldn't be surprised Summoners having this issue too.
Hope it will help.

**Comment by shokilicious** [comment]
I tested the issue with the english, french and german game version (also switched language in act) and apparently it's only an issue for the german game langauge. French and english seem to work just fine.

**Comment by ravahn** [comment]
Confirmed the issue with Dark Knight, it will be fixed in the next update.  Machinist Queen was confirmed by someone else in discord to be working with German language selected in both ACT and FFXIV, though.

**Comment by ravahn** [comment]
Closing this - please re-open if the problem continues, but I included the fix in 2.0.3.1, just released.
