### ISSUE TITLE
Automatic PID detection.

### ISSUE THREAD

**Issue by KaneoHunter** [ravahn/FFXIV_ACT_Plugin#236]
Issue:
ACT reading "unknown zone" with nothing recorded about XIV.

When:
Started after updating to the 2.3.0.2 patch 3 days ago.

Troubleshooting:
I redownloaded the latest version, ensured it was unblocked before extracting.
Closed and re-opened ACT ensuring I was running as admin.
Confirmed that ACT wasn't establishing a network connection with the "Test Game Connection" button.
I refreshed the FFXIV Process ID list.
Double checked the process ID's in task manager, 18104 is my dx11 FFXIV game, weirdly the other PID shown (2292) I couldn't find in the task manager, so I'm not sure what it relates to!

Temporary Solution:
I changed my PID from Automatic to 18104 that was detected, ACT immediately began detecting zones and parsing perfectly.

Other stuff:
Another weird thing is nobody else I've spoken to has had this issue, but if there's anyone else out there who's ACT has suddenly stopped tracking things, just go to "FFXIV Settings" and try the various process ID's in the list to see if it fixes it.

The only things I do differently to most people, is I launch the game via XIVLauncher with auto-login, and also use wtfast as a VPN for the game, but this was the case before the latest update, and I never had any similar problems beforehand.

If I can give you any more information to work out what caused this, I'm happy to help!

**Comment by mreith101** [comment]
Powershell is event driven you should be able to happily grab process id for any process.

**Comment by ravahn** [comment]
ngld (Discord moderator) thinks he tracked down this, or a related problem.  I've changed the process detection to no longer abort when it encounters an exception with just one process.  This will be included in the next release.

**Comment by ravahn** [comment]
This should be fixed in  [release 2.6.3.3](https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/2.6.3.3)
