### ISSUE TITLE
Mac Port

### ISSUE THREAD

**Issue by worenga** [ravahn/FFXIV_ACT_Plugin#244]
Are there known ways to run the FFXIV Plugin under Mac?
If not how much work would porting it to .NET Core be?

**Comment by ravahn** [comment]
We've been talking about this occasionally on Discord.  Currently ACT and the FFXIV plugin can run on Linux within WINE, but MacOS had some sort of incompatibility - I think the game process was not accessible from within WINE, so ACT couldn't connect to it? something along those lines.  It did not look like a problem that can be solved by configuration or minor code changes.

Aditu (Author of ACT) has considered a rewrite to support .Net Core, but  has not decided to start it yet.  Until ACT runs on .Net Core, my plugin probably cant access the game process on MacOS.  Even if it ran on .Net Core, though, there is some question of whether a .Net Core app can access game memory and network packet data effectively.  We won't know unless we try, but I don't see it happening in the next few months.

**Comment by valarnin** [comment]
Going to dump some info here so it's not lost to the Discord history.

To clarify, a lot of things had to align for the plugin to work on Linux to begin with. It's entirely possible that it could work on Mac, but someone on Mac with a lot of technical knowledge would have to put in the effort to get it to work.

Here's a quick list of the requirements:

1. I think it's generally required that you be running the DX11 version of FFXIV, and I have no idea if that's the case for Mac. If not, or if Mac has its own executables running in its wine environment that only exist for Mac, the plugin won't ever work for Mac.
2. Must be able to run ACT within the same wine prefix and wine server that FFXIV is running
3. Must be able to install .NET Framework into the FFXIV wine prefix at least to 4.5 for ACT to work, but more realistically all the way to 4.7.2 for additional plugins to work
4. ACT process must be able to read FFXIV process memory. No clue what the security implications would be on Mac for this.
5. ACT process must be able to open a raw socket connection to accept the same packets that the FFXIV process receives. Again, no clue what the security implications are for Mac for this. On Linux, we have to use the `setcap` program to set capabilities on the main wine executables and jump through a whole bunch of other hoops to make this work.

The Linux setup is scripted out at [my github for linux](https://github.com/valarnin/ffxiv-tools) for reference.
