### ISSUE TITLE
FF XIV Update

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [ravahn/FFXIV_ACT_Plugin#247]
Update for 5.2 update ? Signature seems to need to be updated

**Comment by EQAditu** [comment]
The plugin author is on vacation until the end of the week and the patch changes are more breaking than expected.  You'll have to be patient for an update, I'm afraid.

**Comment by whuizenga** [comment]
> Ravahn Yesterday at 9:21 AM
> Patch 5.2 was released this morning.  Quick DX11 mode review finds that Chatlog vtable signature broke, the MobArray signature broke, and the Target overlay signature broke.  These are three core signatures used by both memory scanning and network packet reading, so the parser is indeed not going to work until it gets an update.

**Comment by atom0s** [comment]
If it helps, for the current x64 client:

Chat Log:
```
48 8D 05 ?? ?? ?? ?? 48 8D 8E 80 00 00 00 48 89 06
```

Mob Array:
```
48 8b 42 08 48 c1 e8 03 3d a7 01 00 00 77 28 8b c0 48 8d 0d
```

Target:
```
41 bc 00 00 00 e0 41 bd 01 00 00 00 49 3b c4 75 56 48 8d 0d
```

**Comment by werewolfboy13** [comment]
Another post:

Most of the work is done, but there are a couple bugs left, one of which critically affects parse results, so I can’t release a beta tonight.  I’m driving all day Friday.  I expect to release a beta on Saturday mid-day, if all goes well.

**Comment by richterk** [comment]
> Another post:
> 
> Most of the work is done, but there are a couple bugs left, one of which critically affects parse results, so I can’t release a beta tonight. I’m driving all day Friday. I expect to release a beta on Saturday mid-day, if all goes well.

Is there anything I can help with?  This tool is ridiculously valuable.  I'd love to help if you're running into issues. :)

**Comment by werewolfboy13** [comment]
There is an beta out in the beta channel in the discord right now.

**Comment by ravahn** [comment]
Official release is out, so closing this issue.

**Comment by Cope93** [comment]
Same issue as of today since ff patched
