### ISSUE TITLE
Broken for 5.3

### ISSUE THREAD

**Issue by chudders1231** [ravahn/FFXIV_ACT_Plugin#255]
It seems that 5.3 has broken the parsing i think. There is an error given by ACT referring to needing an update from FFXIV_ACT_PLUGIN.

Failed: Found FFXIV, but cannot detect one or more FFXIV memory signatures.  If FFXIV was recently updated, this may require an update to FFXIV_ACT_Plugin.

**Comment by jklock** [comment]
+1 Same error:

Failed: Found FFXIV, but cannot detect one or more FFXIV memory signatures.  If FFXIV was recently updated, this may require an update to FFXIV_ACT_Plugin.

**Comment by Salithox** [comment]
+2 Same error:

Failed: Found FFXIV, but cannot detect one or more FFXIV memory signatures. If FFXIV was recently updated, this may require an update to FFXIV_ACT_Plugin.

**Comment by kaizerfreak** [comment]
+3

**Comment by EQAditu** [comment]
Stop posting "me too" messages.

With each game patch, 90% of the time the executable is updated and this will *always* require a new version of the plugin.  **Always.**  I'll ignore the initial poster not knowing this, but the "me too" posts help nothing and get annoying.
