### ISSUE TITLE
BNpcName field is zero in added combatant network log lines

### ISSUE THREAD

**Issue by quisquous** [ravahn/FFXIV_ACT_Plugin#256]
https://xivapi.com/BNpcName/2928?pretty=true

Example:
`03|2020-08-13T07:58:43.4910000-07:00|4001d931|Skogs Fru|0|32|0|0||0|3184|22446|22446|0|10000|0|0|83.69178|131.8231|46.58101|-1.706436||49aa4afcd6e2ccfeadbb806e84026a50`

Expected:
`03|2020-04-26T19:57:19.4130000-07:00|401086b2|Skogs Fru|0|32|0|0||2928|3184|22446|22446|0|10000|0|0|-136.0297|-602.312|34.44824|1.972106||b7ea64f1b88abb41dbaae7bfd8c401ad`

This is the cause of https://github.com/quisquous/cactbot/issues/1673 which filters by BNpcName.

**Comment by ravahn** [comment]
This could be true.  I did try to verify this field, but I may have made a mistake.  Can you confirm this happens in DX11 ffxiv? dx9 and dx11 use different structs.

**Comment by quisquous** [comment]
Yeah, this is dx11.

**Comment by ravahn** [comment]
Fixed in v2.0.6.3.  Closing.

**Comment by Jaehyuk-Lee** [comment]
This is happening same in Korean plugin for v5.3 patch. Is this problem of Parser?
