### ISSUE TITLE
Potency parsing not properly accounting for hitting multiple targets

### ISSUE THREAD

**Issue by chausies** [ravahn/FFXIV_ACT_Plugin#257]
I'm a huge fan of the potency parsing mode. One bug/enhancement I noticed, though, is that it doesn't properly account for potency inflicted on multiple targets.

For example, if a 200 potency AoE move hits 7 targets, it's only registering as 200 potency, not 1400 potency. Would it be terribly difficult to properly account for an calculate the total potency inflicted to all targets? Also, it should properly handle moves like Standard Finish, which deal 1000 potency to the first target, and 750 to all others.

Many thanks!

**Comment by ravahn** [comment]
Potency parsing has a loyal following, but my implementation has quite a few gaps.  Any skill with variable potency or more than basic combo potency effects is logged as zero potency today.  Fixing this requires custom code for each of those skills, or coming up with a way of encoding & detecting that variability.  It isnt something I want to take on right now.   so, potency parsing for the near future will remain inaccurate.

In your specific case, if an AOE hits 7 targets, there should be 7 lines in ACT showing the effect on those targets, each with 200 potency.  ACT registers damage (or heals) on a specific target, it wouldn't make sense in ACT to show only a single line for an AOE with 1400 potency.
