### ISSUE TITLE
No overlays are showing

### ISSUE THREAD

**Issue by lordkabal26** [ravahn/FFXIV_ACT_Plugin#26]
Running latest version pulled from inside ACT which is 1.4.0.7

![issue with overlay](https://cloud.githubusercontent.com/assets/6248212/8437893/309664f8-1f30-11e5-8fd9-72aa9170913e.png)

latest hotfix broke the overlay since it was working fine yesterday.

**Comment by Griever92** [comment]
Confirming this to be an issue for myself and others i've spoken with.
Parsing does not appear to be processing properly either as DPS values are being output as 0, while attack powers are showing proper values.

**Comment by Zero-Shift** [comment]
That issue seems to stem from an overflow in relation to encounter times. At a few points I saw the encounter time jumped to 12 hours!

1.4.0.7 seemed to fix the overflow for me

**Comment by ravahn** [comment]
Confirmed overlays are broken in 1.4.0.7 with dx11  version.  They seem fine with dx9 version, although in both versions they are turning on click-through by default for some reason on my pc.

Have a fix in the works but going to wait until I have time to review a couple things before I release it.

**Comment by lordkabal26** [comment]
After updating, Target and Focus target function for the hp gauge overlays however target of target and hover target are still non functional on DX11

**Comment by Acrys** [comment]
I updated to 1.4.0.9, and HP overlay is still not functioning with these options on DX11. http://puu.sh/iLLEp/201403a6a4.png
Ticking any options off/on doesn't seem to ever make it appear.
