### ISSUE TITLE
"Main" tab doesn't show anything

### ISSUE THREAD

**Issue by Keitenxx** [ravahn/FFXIV_ACT_Plugin#260]
Hi there. I did a fresh install of the ACT software following the latest guide but it doesn't work for me. I already had ACT installed once but i uninstalled it alongside FFXIV last year and now i have this problem after the installation: in the Main tab it doesn't show the parses. I did all things to get the software working (firewall exeption, administrator everything, connection test was all good) Logs seems right to me, shows the combat log but on the program i can't see this. Seems to track my character so i don't know what's going on. Can i send a log to be controlled?

**Comment by kentwongg** [comment]
It's probably not updated for the new patch.

**Comment by ravahn** [comment]
Yes, the hotfix broke the FFXIV_ACT_Plugin's ability to read network data, which prevented network or winpcap mode from working until I released an update.  I just posted the update, so please download the latest version of the plugin in the usual way.  Version should be 2.0.7.4.

Closing this issue.
