### ISSUE TITLE
ACT FFXIV "blocked" by Firewall

### ISSUE THREAD

**Issue by Drudicta** [ravahn/FFXIV_ACT_Plugin#261]
The parser believes it's blocked by a firewall, though it's had an exception for several years. This started at 6:25 PM MDT.

**Comment by EQAditu** [comment]
Delete the old rule, make sure that Windows believes your network is "Private", and let the plugin re-create your firewall rule by using the test connection button.

**Comment by Drudicta** [comment]
Worked like a charm, Thank you EQAditu.
