### ISSUE TITLE
Capitalize effect ID in 0x1A lines

### ISSUE THREAD

**Issue by quisquous** [ravahn/FFXIV_ACT_Plugin#266]
Example: `26|2021-05-02T17:28:54.9260000-07:00|8a0|Blind To Rage|9999.00|E0000000||4001843D|Raven's Image|00|2042400|||a642d1288b80f63710def0a6ed548e1c`

It would be nice if `8a0` were capitalized the way other hex ids like `4001843D` were.

**Comment by ravahn** [comment]
I went through the alpha branch and made all hex numbers use the same capitalization in log lines, so this should be resolved now.
