### ISSUE TITLE
ACT is delayed - "Log parsing lagging behind" 

### ISSUE THREAD

**Issue by healrsadjust** [ravahn/FFXIV_ACT_Plugin#268]
Each time I click onto my other monitor, it bothers my ACT and causes it to delay until I restart it. This has been going on for quite sometime and can't seem to find anywhere that resolves the issue.
**"x Log Parsing lagging behind
Log line parsing has been behind for 10 seconds. A plugin subscribed to BeforeLogLine/OnLogLine may be processing syncronously and taking too long."**
[https://gyazo.com/ecb56b5164f529199bc6222fb212336a](url)

**Comment by ravahn** [comment]
@healrsadjust This is likely a complex interplay between ACT, FFXIV, Overlay Plugins, and the video driver.  I recommend you join the ACT discord (invite 9tHJ7s2P3r) and ask for help in the troubleshooting channel.  It is unlikely a problem with the ACT FFXIV Plugin.
