### ISSUE TITLE
HP overlay no longer shows on latest version.

### ISSUE THREAD

**Issue by Acrys** [ravahn/FFXIV_ACT_Plugin#27]
Worked fine on the version on DX11 before the one that was released most recently, not sure what's up with it. Toggling options/moving it doesn't bring it back.
Dx11.

**Comment by lordkabal26** [comment]
It's already been confirmed in issue number 26, just waiting on a fix at this point.

**Comment by ravahn** [comment]
Fixed Target, Focus Target, and Target of Target. I still need to investigate Hover target, but I'll reply on issue #26 when that is done.

Closing this as a duplicate.
