### ISSUE TITLE
Canceled abilities count as incoming damage on the combatant casting them

### ISSUE THREAD

**Issue by valarnin** [ravahn/FFXIV_ACT_Plugin#271]
As reported on Discord, if a player cancels a cast that cast will show as a no-damage canceled ability for the player. See:

https://discord.com/channels/551474815727304704/551476873717088279/883625472880152646

**Comment by ravahn** [comment]
Working on this now.  I am linking the cancellation data pulled from ActorControl to the Starts Casting data, in order to retrieve the target id.

**Comment by ravahn** [comment]
Should be mostly fixed in  [release 2.6.2.3](https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/2.6.3.3)
