### ISSUE TITLE
Suggestion: support for parsing ObjectSpawn packets

### ISSUE THREAD

**Issue by hyskylord** [ravahn/FFXIV_ACT_Plugin#272]
ObjectSpawn packet contains log lines for spawning of objects that doesn't appear in the enemy list (e.g. Exaflare etc.). It will be helpful for making many triggers with this information.

**Comment by ravahn** [comment]
This may sound like a good idea, but it moves the ACT FFXIV Plugin beyond a combat parser into something that allows players to react to game behavior in an encounter.  While I don't (and can't) put any limitations on what other plugins, I would like to not disrupt game balance too much, and so I prefer to focus on combat parsing to improve player skill.  So, I do not plan to include object entities in the combatant list.

Much of the data used by my plugin is made available to other plugins through various interfaces, so someone could for example create a plugin which listens to the network packets and reacts to particular events of interest.
