### ISSUE TITLE
Characters with the same name are combined on the parser

### ISSUE THREAD

**Issue by Airomatren** [ravahn/FFXIV_ACT_Plugin#273]
If you have characters with the same name but from different servers they will combine on the parser.

**Comment by ravahn** [comment]
The next version will include a fix for this - appending servername to the end of player name when multiple players with the same name but different IDs detected.  Currently released in beta version 2.6.2.9 on Discord beta channel.

**Comment by ravahn** [comment]
Fixed in [release 2.6.2.3](https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/2.6.3.3)
