### ISSUE TITLE
ACT tries to load an old plugin despite the update

### ISSUE THREAD

**Issue by WutsKraken** [ravahn/FFXIV_ACT_Plugin#274]
![image](https://user-images.githubusercontent.com/91640188/144975625-d8439621-bb44-4db0-b64e-6eed69ee34c4.png)

This is the error I get for some reason whenever I try to load up ACT

The plugins are all up to date it seems, but for some reason ACT is still trying to load n old version of Overlay Plugin

**Comment by ravahn** [comment]
This is best handled on the ACT FFXIV Discord, and is unrelated to the ACT FFXIV Plugin.
