### ISSUE TITLE
Might be a dumb question but I can't figure it out

### ISSUE THREAD

**Issue by cahl1337** [ravahn/FFXIV_ACT_Plugin#277]
My combat log is logging to the file but in the main tab of ACT it shows a random date (it's 10am now but the empty log is like 6pm). How do I get the main tab to start showing the current log again? I reinstalled and it somehow saved whatever i screwed up.

**Comment by ravahn** [comment]
FFXIV was just patched to version 6.08.  Game updates usually require updates to the plugin.  Plugin update was released yesterday afternoon, so this should be resolved now.
