### ISSUE TITLE
Error while processing packet at position

### ISSUE THREAD

**Issue by philarr** [ravahn/FFXIV_ACT_Plugin#28]
(1.4.0.8) Using spells like fester and painflare is not recorded and will show errors like:

MEMORY ERROR: 254|2015-07-02T17:19:05.8350000-07:00|Error while processing packet at position [120].  4000000087D1291087D12910030000001400430100002C00FAD49555000000001100536601000000B5000000E80300000000000000000000000000004C2DDEF43800000087D1291087D12910030000001400420100002C00FAD49555000000001600000002000000300100000100000000000000000000E0A001000087D1291087D12910030000001400400100002C00FAD49555000000001B3C3C00882800008828000049264926E80300006D010A000000F041000000E06F010A000000F041000000E0300101000000000087D12910270302000000F04187D129100000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008801000087D1291087D12910030000001400480100002C00FAD49555000000006D010A000000F041000000E06F010A000000F041000000E0300101000000000087D12910270302000000F04187D129100000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000E00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000087D1291087D129100300000014009F0100002C00FAD49555000000001B3C3C00000000000000000040E602009400000087D1291087D12910030000001400460100002C00FAD4955500000000C011004000000000B5000001B50000006900000040D700009A99193F0000DCE5C011004000000000000000E0120000022703000000000000000000000000000000000000000000000000000003050700F80400000000000000000000000000000000000000000000000000000000000000000000Object reference not set to an instance of an object.|   at FFXIV_ACT_Plugin.Memory.ScanPackets.ProcessPacket(Byte[] buffer, Int32 currentPos, Int32 messageSize, DateTime packetDate)    at FFXIV_ACT_Plugin.Memory.ScanPackets.ProcessNetworkBuffer(NetworkConnection connection)

**Comment by ravahn** [comment]
This is a bug - 1.4.0.8 added some code which didn't check for a null actor.  Just updated to v1.4.0.9, can you try that version and let me know if you still get the error?

**Comment by Zythrawl** [comment]
I think i'm getting the exact same thing. Everyone's DPS is way lower than it should be

**Comment by ravahn** [comment]
Zythrawl - is this after 1.4.0.9?

**Comment by Zythrawl** [comment]
Testing it right now

**Comment by Zythrawl** [comment]
It seems to have fixed it. Not getting any errors whatsoever and the DPS is where it should be.

**Comment by ravahn** [comment]
Sounds good, thanks for testing.  When a network buff didn't record the specific player that cast the buff, it would raise that error due to a change in 1.4.0.7
