### ISSUE TITLE
Chinese version parse error and may stop working

### ISSUE THREAD

**Issue by chun1324** [ravahn/FFXIV_ACT_Plugin#281]
OverlayPlugin 0.18.2

1. Plugins
2. FFXIV ACT Plugin
3. Parse Option
4. Language: 中文
5. General
6. Check the log

Error message:
`Error: Failed to find enmity memory for 5.5: charmapAddress,inCombatAddress`
`Further enmity errors won't be logged.`

**Comment by blacc000** [comment]
您的邮件我已收到。

**Comment by chun1324** [comment]
This issue created in wrong page. Please ignore it
