### ISSUE TITLE
ACT crashing when coming back into focus

### ISSUE THREAD

**Issue by Baleoce** [ravahn/FFXIV_ACT_Plugin#31]
Config:

Latest ACT
Latest FFXIV Plugin
Latest Rainbowmage
OS: Win 8.1 Pro 64bit
CPU: i7-950 @3.8GHz
6GB DDR3 RAM
Mobo: Gigabyte X58A-UD3R
GPU: MSI GTX 760
Dual Monitor 1080p @60Hz (Playing FFXIV in borderless windowed mode)
Nvidia Shadowplay persistent in background
ACT running in administrator mode, parsing from network data

I run ACT and I can mess about with the settings, and everything works fine. I see the main tab giving realtime results and the overlay shows this too. Everything works perfectly, then I put the game in focus either by Alt-Tab or clicking on it, and again it works fine.

The trouble I have, is after I've been parsing for a while, and then I switch the main ACT window back into focus. It crashes every single time. and I can tell it's happening as soon as I Alt-Tab or click back to it, because I can see ACT on my second monitor with the timer counting up from an encounter, and as soon as I switch to it the timer hangs and it becomes unresponsive until I kill the process.

This has actually been happening for a while, and isn't something that's new to either this version of ACT or the plugin. I just wanted to attempt to get to the bottom of it. If it turns out to be an ACT issue instead of the plugin, then I'll seek out the official forum for some answers.
Many thanks in advance.

**Comment by Squall-Leonhart** [comment]
appears to be a collision with shadow play, since i don't use it and have none of these problems.

**Comment by Griever92** [comment]
As a ShadowPlay user, I also have none of these issues, so I doubt it's as simple as that.

**Comment by ravahn** [comment]
No idea what this could be, but do you have the FFXIV Plugin overlays (Target HP, Focus Target, etc) turned on? if so, can you try turning them off to see if they are the cause?

**Comment by Baleoce** [comment]
Thanks all, rav that seems to have worked (i just hid every option on the ffxiv overlay plugin). But I haven't played enough since to be able to say for certain. I'll update if it does it again.

**Comment by Baleoce** [comment]
Was about to close it up and noticed that it had happened again. No idea to be honest. Do you think if you have poor internet, that could affect the network parsing and cause it to hang?

**Comment by ravahn** [comment]
Bad network performance should not affect it, all of the memory scanning and network scanning is performed in threads that do not touch the UI thread, it just writes to a file.

The overlays and HP logging do touch the game memory directly but even so they shouldn't hit a deadlock since I think that the only shared resource they access is the process info. 

No idea what this could be, but I'll keep poking around.
