### ISSUE TITLE
Damage numbers drastically lower in ACT vs. in-game

### ISSUE THREAD

**Issue by bmelts** [ravahn/FFXIV_ACT_Plugin#32]
Got a weird issue that no one else seems to be having - comparing the raw damage listed in the battle log with what's recorded in ACT, the ACT number is dramatically lower than the in-game number (by a factor of about 3.9). 1.4.1.0, network parsing enabled, nothing in the Parser Messages box. Am I doing something wrong? Am I misunderstanding these numbers?

An encounter where I just right-click on the enemy (doing a single auto-attack) and then leave:

FFXIV (total raw damage: 374): 
![image](https://cloud.githubusercontent.com/assets/3125/8635703/440c553c-27e7-11e5-848a-8688405693d8.png)

ACT (total parsed damage: 96):
![image](https://cloud.githubusercontent.com/assets/3125/8635705/65bec034-27e7-11e5-8af2-ec576dd7705d.png)

Using a skill too:

FFXIV (total raw damage: 990):
![image](https://cloud.githubusercontent.com/assets/3125/8635710/a3e30910-27e7-11e5-90ab-90841cfe3dc6.png)

ACT (total parsed damage: (254):
![image](https://cloud.githubusercontent.com/assets/3125/8635711/b6dc8488-27e7-11e5-8cd6-24241c507ffd.png)

**Comment by ravahn** [comment]
Very odd.  Can you hit a striking dummy for a little bit and then email the logs to ravahn (at) hotmail.com?

You can find the logs by going to the plugins -> FFXIV Settings tab and clicking the 'Open FFXIV Log Folder' button.

**Comment by Maledictumrus** [comment]
Greetings. I have the same problem. Do you need me to write logs and send them?

**Comment by nvll** [comment]
I see this as well in the current release.

**Comment by nvll** [comment]
![image](https://cloud.githubusercontent.com/assets/62597/22195039/a092505e-e0fa-11e6-802d-2345eb6b16b0.png)
