### ISSUE TITLE
(Request) calculate the real healing

### ISSUE THREAD

**Issue by Ninguengon** [ravahn/FFXIV_ACT_Plugin#37]
Hi, sorry for my English but I was wondering if you could add a new "Formatting Element" to calculate the effective heal.
We have the "healed"  {healed%} and the "overhealing" {OverHealPct}, I think with this it could be calculated the real healing in percentage.
I do not know how complicated it would be to implement this but as a healer this information would be very useful.

Thank you.

**Comment by Sinistralis** [comment]
My overlay for Rainbow Mage's overlay has this functionality, although it is slightly inaccurate since OverhealPct comes down already rounded.
