### ISSUE TITLE
Encounter.tohit is calculated incorrectly

### ISSUE THREAD

**Issue by Sinistralis** [ravahn/FFXIV_ACT_Plugin#38]
This information is coming from RainbowMage's plugin, but I am almost positive his plugin is a passthrough of information from this plugin. If I am wrong, feel free to redirect this bug.

As it currently stands, Encounter.tohit is calculated by summing the tohit of all combatants and averaging it, which ends up being incorrect. It should be summing all hits and swings, and dividing them.

Heres an example:

ENCOUNTER:
hits: 49 
misses: 5
swings: 54
tohit: 92.19
TOHIT: 92

COMBATANT 1:
hits: 22
misses: 0 
swings: 22
tohit: 100.00 
TOHIT: 100

COMBATANT 2:
hits: 27
misses: 5
swings: 32
tohit: 84.38
TOHIT: 84

Actual Hitrate is 49/54, which is 90.7. Reported hit rate is 92.19 ((100 + 84.38)/2)

**Comment by ravahn** [comment]
Agreed, this sounds like a bug in the calculation.  

Looking at the FFXIV plugin code, it does add an incoming (not outgoing) hit rate column to each combatant, but not the encounter.  The ToHit% variable records outgoing hit rates, which is part of ACT itself.  I could override its behavior, but the ACT Author (Aditu) is responsive, so could you post this to him? His email is in the ACT About tab.
