### ISSUE TITLE
Parsing from Network Data not working.

### ISSUE THREAD

**Issue by sucht** [ravahn/FFXIV_ACT_Plugin#41]
I'm on Windows 10 x64 running ACT with your Plugin(x64) and Parsing from Network Data is not working :(

When i click on "Test Game Connection" under "FFXIV Settings" i get:
![error](https://cloud.githubusercontent.com/assets/7991008/9287114/8fca2aa0-4306-11e5-845f-70164d91be0e.jpg)
followed by:
![error2](https://cloud.githubusercontent.com/assets/7991008/9287119/de128c3e-4306-11e5-9ac1-18dc1ccd8a5b.jpg)
even though i have given it permission on the Windows Firewall for everything coming in and going out(TCP/UDP).
and i always run ACT x64(Advanced Combat Tracker.exe) as Administrator.

**Comment by Dyspathy** [comment]
+1 tried everything, firewall on/off, access granted, admin mode, pcap driver and I can't get the plugin to read from network data.

**Comment by ventus182** [comment]
+1

**Comment by ravahn** [comment]
This is a recurring problem, it usually is due to some issue with the built-in windows firewall.  The simplest solution is to install WinPCap and change the "Parse Mode" setting for the plugin to "WinPCap Network".
