### ISSUE TITLE
Detect the actual start and stop of encounter

### ISSUE THREAD

**Issue by DFlame69** [ravahn/FFXIV_ACT_Plugin#42]
It currently appears that the plugin relies on timers to end encounters. Couldn't the ingame battle mode be detected for use at determining the start and stop of encounters?

**Comment by ravahn** [comment]
I recall testing this and finding that combat would stop when a player disengages after a certain amount of time, even though other group members were fighting.  So, I prefer to leave this as-is, since the definition of when an encounter starts/ends isn't as clear-cut.
