### ISSUE TITLE
weird damage calculatoins

### ISSUE THREAD

**Issue by P2K9** [ravahn/FFXIV_ACT_Plugin#44]
I'm not sure what it was but after the most recent update (1.4.2.0) ACT has been reporting some weird numbers. In A1S today on Faust it was reporting our SMN doing over 3k DPS on my ACT, our PLD's ACT was reporting that the SCH was doing 64k DPS. And that was just tonight. On Monday night in A2S we had the same issue - on our clear run the SMN's DPS was almost 10k. Here's a screenshot I took after we cleared Faust with my ACT mini window http://i.imgur.com/ST0boIR.jpg

**Comment by ravahn** [comment]
I see some issues on Opressor that I'm working on, but Faust looks ok.  Can you email the Network_10282015.log file to me at ravahn(at)hotmail.com?

**Comment by ravahn** [comment]
What appears to be happening is a bug with processing of the Damage Down debuff from 3000 Tonze Missile's Heavy Impact attack.  the parser is not purging it when it drops / encounter ends, which causes the DoT simulator to incorrectly determine the relative player power when calculating the DoT ticks for future encounters.

Testing various ideas to fix this, so thanks a lot for the log!

**Comment by ravahn** [comment]
Just released v1.4.2.1 which should fix this.  Closing the issue for now, but please let me know if you still see wildly incorrect DoTs.
