### ISSUE TITLE
Enkindle DoT damage not correctly recorded (estimated)

### ISSUE THREAD

**Issue by khalid417** [ravahn/FFXIV_ACT_Plugin#45]
When using Ifrit-Egi (presumable the same issue with titan-egi), using the skill enkindle as a summoner will correctly record the initial hit damage, but incorrectly record the additional (5) DoT ticks. 

Example would be, initial hit of 2750 and resulting DoT damage of 20 damage per tick.

**Comment by ravahn** [comment]
Old issue, but this appears to be fixed now.  At least, ifrit-egi DoT ticks from Inferno are being simulated in a handful of parses I reviewed.
