### ISSUE TITLE
Data not parsing after ff14 patch 3.1

### ISSUE THREAD

**Issue by zbtiqua** [ravahn/FFXIV_ACT_Plugin#46]
Does this plugin require an update for ff14 patch 3.1?

All my settings are the same as before the patch, when it was working perfectly. Running as administrator, exception in firewall, etc etc.

I am running also with Enmity Overlay v1.6.6.0 which updated today for patch 3.1.

**Comment by Iceazuk** [comment]
It will need an update to work with 3.1 the offsets/signatures would have changed for the new patch.

**Comment by Iceazuk** [comment]
looks like it was updated as I just got the download message in ACT.

**Comment by ravahn** [comment]
Yes, I have updated the plugin for FFXIV 3.1.  There is still one remaining bug with Memory mode parsing - DoT ticks will not be simulated.  Network mode should work 100% now, though.
