### ISSUE TITLE
Not parsing

### ISSUE THREAD

**Issue by Lev2540** [ravahn/FFXIV_ACT_Plugin#48]
So I have been using ACT since forever and just recently (3 days ago) it has completely stopped working. I just wont show the encounters on the mini nor main table. At the top of the window it does show unknown zone which i know is wrong. That said here is what I have tried so far:
Checking to make sure it latched via the check connection option under FFXIV plugin
Re-installed
Re-downloaded FFXIV plugin
Confirmed log file locations
Tried turning on and off network parsing neither seemed to make a difference.
White listed in firewall
Turned off firewall

I also always run ACT as admin.

**Comment by ravahn** [comment]
Are you running FFXIV patch 3.20? if so, this is very confusing.  Go to Plugins -> FFXIV Settings and click the 'Open Log Folder' button.  Look at the latest log - is it from today, and is there much data?  if not, there should be one or more lines in there like this:

251|2016-02-24T10:04:51.7397295-08:00|FFXIV Connection Found: 199.91.189.148:55007 -> 192.168.1.34:57168

that indicates that the plugin is able to identify network traffic from the game.  

If the 'Test game Connection' button doesn't show an error, it's at least able to connect to the game process, so it is surprising that there is no difference with network parsing turned off.

**Comment by Lev2540** [comment]
I have been able to get it to work recently by going and selecting the FFXIV Process ID manually every time I start ACT. Sometimes there is only 1 and others there are 2 where I have to test the game connection on both of them to find the one that succeeds. Its not a big deal anymore.

**Comment by trfunk** [comment]
Hello,
It looks like I ran in exactly the same problem, expect selecting the PID doesn't seem to work.

It doesn't throw an error, tells me that network data & game data is aviable, updates the log, but doesn't parse/shows anything in the main table. I attached my network log (my game is on german).

I also run act always as an admin.

[Network_20160309.zip](https://github.com/ravahn/FFXIV_ACT_Plugin/files/165138/Network_20160309.zip)

**Comment by ravahn** [comment]
Hi trfunk, for some reason the plugin is detecting the network connection information, but no data is coming in.  This is very difficult to troubleshoot.

One alternative is to use the free WinPcap driver - the FFXIV plugin now supports it.  You can download from here: http://www.win10pcap.org/
then, go to Plugins -> FFXIV Settings and check the "Use WinPCap Network Driver" checkbox inside ACT.

One warning - I am not affiliated with WinPCap, so I cannot guarantee that it will not cause any problems with your system.  I have it installed in mine, but it includes a windows kernel driver to access the network data, and these sorts of things sometimes do not play nice with other network kernel drivers.

If you do give it a try, please let me know if it resolves the problem.

**Comment by trfunk** [comment]
Hello,
I did try the WinPcap driver and it seems to work fine. Numbers seem accurate, crosschecked with a friend.

**Comment by hsluoyz** [comment]
Hi,

You would like to try Npcap: https://github.com/nmap/npcap

It's a update to original WinPcap.

**Comment by hbq0449** [comment]
I have the same problem like trfunk, the network log also look the same. But win10PCap dosen't work for me. Do vpn affect the network parsing? If so, what can I do about it? Without vpn, I even can not login.

**Comment by ravahn** [comment]
Yes, some VPNs do affect network parsing.  I did some testing a few years ago and added an option to select a specific IP Address to listen to, but if the vpn bypasses the network interface somehow then it just isnt possible for the plugin to parse.
