### ISSUE TITLE
Invalid signature spam since 3.2

### ISSUE THREAD

**Issue by Squall-Leonhart** [ravahn/FFXIV_ACT_Plugin#49]
Sure this isn't news to you, but the plugin message log is filling with invalid signature messages.

**Comment by ravahn** [comment]
Yes, DX11 target and Zone ID are broken.  I've fixed them and am testing now.

Have not examined DX9 yet. 

Should have a release out later today.

**Comment by ravahn** [comment]
Released v1.4.2.6 to fix network mode.

Memory mode is still not working, will continue working on it.

**Comment by Squall-Leonhart** [comment]
Would memory mode not working explain why alliance data is missing from ACT?

i use network parsing myself, but for some reason only my party's output is appearing, and yes, alliance is selected in the options.

also i see this when in void ark.

WARNING: [07:36:16.31] Unknown Effect Type [38]. 40000EDE:Echidna:366:Attack:10663777::0:0:0:0:0:0:0:0:EB070107:81138E:38:8002C3:0:0:0:0:10081:20770:5214:5214:1000:1000:291.8113:-139.0016:-383.9726:1682513:5525760:27164:27164:1000:1000:291.2794:-135.4849:-383.9667

**Comment by ravahn** [comment]
Released v1.4.2.7 - this should fix the parse filter option, and restore parsing with network information disabled.  Closing this issue.
