### ISSUE TITLE
ACT no longer detecting Party/Alliance DPS

### ISSUE THREAD

**Issue by Griever92** [ravahn/FFXIV_ACT_Plugin#50]
Since updating to 1.4.2.6 **from** 1.4.2.5, ACT is no longer detecting any party or alliance actions/DPS readings aside from my own.

Occasionally other names will appear, but they are given a value of 0 as it has not detected any damage it appears.

**Comment by ravahn** [comment]
I suspect you are using the Parse Filter = Party or Alliance option.

The signature for party data was fine with this update, but the size of the party structure increased, so it was trying to read the party size at the wrong location.  I've got a fix for DX11 ready, but I want to get memory mode working before I release it.

In the meantime, turn off the parse filter until the next release.

**Comment by Griever92** [comment]
Yep, that's exactly what it was, thanks!

**Comment by ravahn** [comment]
Released v1.4.2.7 - this should fix the parse filter option, and restore parsing with network information disabled.  Closing this issue.

**Comment by Squall-Leonhart** [comment]
I don't see this release anywhere for download yet D:
