### ISSUE TITLE
Duplicate Overlay (Current Target)

### ISSUE THREAD

**Issue by Griever92** [ravahn/FFXIV_ACT_Plugin#51]
Been running into an issue since the 3.2 Update where i'm finding that the Current Target overlay seems to be duplicating to the location of my Focus Target overlay.

It's very easily reproducible, and often the duplicate will remain on screen even while nothing is targeted.
Unfortunately, this sometimes causes some readability issues with my actual Focus Target overlay.

Duplicated overlay for current target seen in bottom left of image.
![issue 1](https://cloud.githubusercontent.com/assets/7936026/13306041/6f5bb162-db1d-11e5-95f3-48f80b596d08.PNG)

When focus target overlay active (can see the color of the HP bar change due to it now being layered on top of the duplicate+transparency+stock UI, this presents some challenges when reading numbers)
![focus](https://cloud.githubusercontent.com/assets/7936026/13306049/7faeba0a-db1d-11e5-9b1d-44ebd89205ad.PNG)

Here are the configuration options set for my overlays.
![config1](https://cloud.githubusercontent.com/assets/7936026/13306047/7fa876f4-db1d-11e5-8dad-6acb6d101ecc.PNG)

![config2](https://cloud.githubusercontent.com/assets/7936026/13306048/7fab28ea-db1d-11e5-8256-afc464b3d5cb.PNG)

**Comment by Squall-Leonhart** [comment]
Occurs during the final boss of Lost City Hard mode usually.

**Comment by Griever92** [comment]
I'm not sure where Lost City comes into play since it occurs everywhere.  
Even after reloading the game and ACT.

**Comment by ravahn** [comment]
Confirmed the focus target bug - the focus target memory area moved by 8 bytes.  Will fix it in the next release, probably tomorrow.

**Comment by ravahn** [comment]
Released v1.4.2.9, can you update and let me know if it is fixed?

**Comment by Griever92** [comment]
Confirmed, appears to be fixed, i've not run into this issue since updating the plugin.
