### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by pancakegithub** [ravahn/FFXIV_ACT_Plugin#52]
I've noticed an odd issue regarding the fonts for the main overlays (for target, focus, etc). I'm not sure if this is somehow an issue on my end, or with the FF14 plugin, or possibly within ACT itself.

Anyways, what the issue is, is if I change the font of one of these overlays to Symbol, the list of fonts for that overlay will only contain Symbol, Webdings and Wingdings. All other fonts will no longer be present for that overly, however the other overlays will still have access to all of the other fonts just fine.

The only fix I've found so far, is to close ACT, navigate to the FFXIV_ACT_Plugin.config.xml in the AppData directory and manually editing the font for the affected overlay to something else (such as Arial), and then relaunching ACT, and the full font list is there again.

**Comment by ravahn** [comment]
Definitely a bug.  I had a restriction on the Font dialog to not allow changing to a different 'Script' (Western, Symbol, etc).

I'll remove this restriction in the next version update, should be released in a day or two.  Thanks for reporting the problem!
