### ISSUE TITLE
Broken by 3.26 :(

### ISSUE THREAD

**Issue by Squall-Leonhart** [ravahn/FFXIV_ACT_Plugin#54]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [MobArray]

**Comment by Swiftray** [comment]
Same problem

**Comment by ravahn** [comment]
Thanks for the reports.  Turned out that the signature was fine, but was located halfway between memory blocks so was not found by the Sig scanner.  It is now fixed.
