### ISSUE TITLE
Add support for displaying Emnity

### ISSUE THREAD

**Issue by xijio** [ravahn/FFXIV_ACT_Plugin#6]
I tried ffxivapp a long time ago and one of the coolest things was the emnity meter.  Helped me learn to be a great tank =D

**Comment by ravahn** [comment]
It looks like someone else made an ACT enmity plugin, so I'm going to defer this functionality to them.  Here's a link to their plugin:
https://github.com/xtuaok/ACT_EnmityPlugin
