### ISSUE TITLE
FFXIV 3.4 Zone IDs

### ISSUE THREAD

**Issue by Krude** [ravahn/FFXIV_ACT_Plugin#61]
They're still missing as of now. I don't have the IDs for all zones yet, but here's a few:

240 - Containment Bay P1T6 [a.k.a Sophia Hard]
242 - The Great Gubal Library (Hard)
244 - The Eyes of the Creator
245 - The Breath of the Creator
246 - The Heart of the Creator
247 - The Soul of the Creator

Might post some others as i encounter them, or maybe someone else wants to contribute.

**Comment by Krude** [comment]
There's also the Palace of the Dead zones, which haven't been added, i just noticed. Seems like each set of 10 floors have one ID. I have these two for now, will confirm the rest of them later.

234 - Palace of the Dead 31-40
235 - Palace of the Dead 41-50

**Comment by ravahn** [comment]
Somehow the updated zone list file I created did not get included in the build, probably a copy/paste  error on my part.  I have all of the above zones, plus a handful more, which will go out soon.

For some reason there are 10 different floors 61-70 for palace of the dead, which may be of interest!
