### ISSUE TITLE
Target Overlay not functioning as of Patch 3.45 

### ISSUE THREAD

**Issue by Griever92** [ravahn/FFXIV_ACT_Plugin#63]
Update/Patch 3.45 appears to have broken the functionality of the overlay which displays HP/Target information.

**Comment by LogosObscured** [comment]
To add, issue only occurs with the DX11 client. Overlay still working with DX9.

**Comment by bfabe8** [comment]
To add, there's a constant spam of "Error: Unable to read signature [Target]" in the Parser Messages window.

**Comment by balthiersake** [comment]
Any plan to fix this for DX11??

**Comment by ravahn** [comment]
Releasing v1.4.2.21 now with the target overlay fixed.  Also found some minor zone updates and skill updates, so included those.

Not sure about the name problem reported by LogosObscured, my network data file looks fine, and parsing seems fine.  Do you have anything unique set in your FFXIV configuration?

**Comment by LogosObscured** [comment]
I'm not sure on terminology, but my log file was showing like this (with win10 dx11):
21|2016-11-01T17:45:21.9240000-04:00|106A033C||07|Attack|40001829||0|0|0|0|0|0|0|0|70105|391|0|0|0|0|0|0|44|44|0|0|1000|1000|0|0|0|16604|16604|4213|4213|950|1000|0|0|0

In any case, It's working fine now, with the update. Really appreciate everything you do ^^
