### ISSUE TITLE
[FFXIV_ACT_Plugin_1.4.2.23] SystemInvalidOperationException. This implementation is not part of the Windows Platform FIPS validated..

### ISSUE THREAD

**Issue by Gristrosia** [ravahn/FFXIV_ACT_Plugin#64]
Hi,

I'm getting this error message when I load the new FFXIV_ACT_Plugin_1.4.2.23 in ACT. I don't have this message, or any issues at all, with the previous version. the plugin seem to load, the tab appears, I didn't try to parse anything yet.

Any way to fix it besides the obvious to disable the enforce FIPS on Windows?
![capture](https://cloud.githubusercontent.com/assets/25066224/21867001/b345072a-d84c-11e6-9ade-9b04c8862a75.JPG)
.

**Comment by ravahn** [comment]
Can you contact me at ravahn (at) hotmail.com to discuss in more detail?

**Comment by 01yt01cs89** [comment]
Hello! I'm having the same issue!  1.4.2.21 was fine but not 23 and 24!

**Comment by ravahn** [comment]
Yes, I've got a fix ready to go in 1.4.2.25 for this.  You wont be able to upload to FFLogs, but ACT will work.
