### ISSUE TITLE
Enmity Parse not working

### ISSUE THREAD

**Issue by Sonlen1414** [ravahn/FFXIV_ACT_Plugin#66]
After a couple of restarts of both FFXIV and ACT as well as a couple of updates to the plugin, it would seem I cannot get the Enmity Parse to work. I was having issues with both Enmity and DPS, but after a replacing the dll itself the DPS side started working, but Enmity still will not show any data.
(Sorry if this is not how to work this, just thought it was a issue and would comment on it)

**Comment by ravahn** [comment]
Unfortunately the Enmity plugin is maintained by someone else, and uses its own memory locations.

I think this is the project which maintains that plugin:
https://github.com/xtuaok/ACT_EnmityPlugin
