### ISSUE TITLE
HP not showing / No parsing

### ISSUE THREAD

**Issue by Kobakage86** [ravahn/FFXIV_ACT_Plugin#67]
Heyo, with the new update out and the new plugin released, somehow my mobs are still showing 0 HP and I'm getting lot's of errors in the Parser Messages regarding Memory Errors, I'm using the 32bit version btw, I haven't changed any settings tho, just replaced the .dll 

Do you need the parser message ? :)

**Comment by ravahn** [comment]
Version 1.4.2.24 of the plugin works with 64-bit only (DX11) due to the changes in 3.5.  I didn't have time to fix both versions yesterday.

I just released version 1.4.2.25, which works with both editions now, so please give it a try.
