### ISSUE TITLE
[ FFXIV_ACT_Plugin_1.4.2.25] "Input string was not in a correct format., StackTrace="

### ISSUE THREAD

**Issue by Gristrosia** [ravahn/FFXIV_ACT_Plugin#68]
Getting this error in the plugin error log tab. I tried to parse, and it parsed fine. 

> ERROR: [18:06:42.691] 15:, Input string was not in a correct format., StackTrace=   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>    at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
>    at System.Convert.ToInt32(String value)
>    at FFXIV_ACT_Plugin.Parse.LogParseData.Process(MessageType lineType, LogEntry entry, String[] data)
>    at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
>    at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)

I tried to delete all the old logs in the /log/ folder, same problem.

Widnows 10 (1607) x64 with FIPS enabled.

EDIT: The error message doesn't show up on my machine with FIPS disabled.

**Comment by ravahn** [comment]
Not sure what is causing this.  Do you have any way to send me a log file so I can test it?  You can email it to me at ravahn (at) hotmail.com if that helps.
