### ISSUE TITLE
HP Overlay does not function in DX11 as of 1.4.2.25

### ISSUE THREAD

**Issue by smakker** [ravahn/FFXIV_ACT_Plugin#69]
Have it enabled but it does not show.

It does show in DX9 however it displays 0/123409823948 HP.

If this is a duplicate, I apologize.

**Comment by chadouming** [comment]
Same problem here, I guess patch 3.5 broke some pointer.

**Comment by Griever92** [comment]
Also experiencing this.

**Comment by ravahn** [comment]
Unfortunately this was a combination of 3.5 and developer error!  Uploading a fix shortly.

**Comment by chadouming** [comment]
Cool, thanks for the fast update

**Comment by smakker** [comment]
Just updated, confirmed fixed in DX11.

Thank you!
