### ISSUE TITLE
Only parsing me or everyone

### ISSUE THREAD

**Issue by xdavenx** [ravahn/FFXIV_ACT_Plugin#70]
Hi
Some of the parsing filer options does not work anymore. If i set it to party or alliance it only parse me. Only if i set it to none it parse everyone. So the party and alliance filters seems off somehow. Before version 1.4.2.25 always had it to "party" in the parsing filter to not get super long list in raids n hunts. Would be awesome if you could have a look at this.

Thx in advance!

**Comment by Rhess86** [comment]
Even after the update, the 1.4.2.26 this still happens.

**Comment by YrAhBeJoP** [comment]
I have the same issue even after last update.

**Comment by bhaal166** [comment]
same problem here

**Comment by Rhess86** [comment]
All these updates and still no fix for this /sad

**Comment by chadouming** [comment]
Make your own plugin if you ain't happy with this one.

**Comment by Rhess86** [comment]
I could, but i won't just because you said that.

**Comment by chrisnorthcott** [comment]
FC mate on DX9 client is reporting this as still an issue even with the latest update.

**Comment by Rhess86** [comment]
Yet another update and still no fix for this, i think he gave up on dx9 for good. rip poor people.

**Comment by ravahn** [comment]
It's not dead, but FFXIV made it so I need to track down a real person to get party functionality tested.  My chocobo used to be sufficient. So, will be a while.

**Comment by ravahn** [comment]
I've hopefully fixed the party detection for 8-man or smaller parties.  24-man still is not working unfortunately, so leaving this open.
