### ISSUE TITLE
Custom Triggers wont work with "new symbol"

### ISSUE THREAD

**Issue by Izilder** [ravahn/FFXIV_ACT_Plugin#72]
Had this issue ever since SE put the special symbols into chatlog - playing on x64

You gain the effect of Enhanced Wheeling Thrust.
You gain the effect of Sharper Fang and Claw.

**Comment by Rhess86** [comment]
Add a .* at the symbol place: 
You gain the effect of .*Sharper Fang and Claw.

Works for everything.
