### ISSUE TITLE
4.0 support

### ISSUE THREAD

**Issue by PommeVerte** [ravahn/FFXIV_ACT_Plugin#73]
Hey guys,

This is an obvious one. I figured an issue to track progress would be a good idea. With stormblood early access out it would be nice to get the plugin working again.

Cheers.

**Comment by ravahn** [comment]
Yep! It's in progress.  I have updated code to use the new memory locations, and the new network packet structure. but now I am working on re-encoding all the ability changes so that DoTs are sane.  Then I need to validate that it actually works.

**Comment by BingSizzlin** [comment]
Hey,

I apologize if this is not the correct place to ask, but ravahn, do you think you could explain the packet structure whenever you find the time?  I understand that getting the plugin up and running is your top priority.

Thanks!

**Comment by toychristopher** [comment]
I also apologize if this isn't a place to ask, but is there a way to donate to this project? Having it be down for this brief period has made me realize how important it is to me.

**Comment by ravahn** [comment]
I've released a beta version of the plugin:
[FFXIV_ACT_Plugin_Beta_1.5.0.4.zip]

Only DX11 mode works, and it requires network parsing for now.  I'll address both of those eventually, but getting the main version working takes priority.

There are still some issues with the DoT simulation, so this is considered Beta.  I need to investigate Gauges more to determine how they affect damage for each class, and possibly incorporate them.  Feel free to share, but it won't go out to the automatic updater until I've had time to do more testing and improvement.

**Comment by ravahn** [comment]
To toychristopher - thank you for the sentiment :) I don't accept funds for a couple of reasons, unfortunately, so please enjoy the plugin.

**Comment by danakj** [comment]
Thank you! Where can we download the Beta? I don't see it on the announcement page or on github releases.

**Comment by danakj** [comment]
Ah I found it in the source tree. https://github.com/ravahn/FFXIV_ACT_Plugin/commit/e0913191e519ad755f4f9f79bd0a58d3698073a7#diff-74f980b55cb4798e9668e2b10d48bab1 for others looking.

**Comment by cairface** [comment]
Appreciate the hard work! Just figured I'd give a heads up that both Caustic Bite and Stormbite (upgraded BRD DoTs) don't work. If you need ability or debuff IDs, I can grab them for you -- not sure how this works internally.

**Comment by ravahn** [comment]
Thanks for the report about BRD DoTs, I've fixed those.

The full release is now available through ACT auto-updater as well as github, so I'm closing this issue.
