### ISSUE TITLE
[Beta 1.5.0.4] LB3 for new jobs getting attributed to player

### ISSUE THREAD

**Issue by xephero** [ravahn/FFXIV_ACT_Plugin#74]
Samurai LB3 is attributed to the Samurai player currently, rather than the separate Limit Break combatant. 

`[12:42:05.313] 15:102D3EEE:John Doe:1EB5:Doom Of The Living:400173A0:Susano:780003:403730:1C:801EB5:0:0:0:0:0:0:0:0:0:0:0:0:283949:4553593:9350:9350:1000:1000:-3.035938:3.8:1:11496:25382:3836:3836:730:1000:-3.066758:0.93:1`

I believe the RDM one is called Vermillion Scourge but I don't have a log line for that one.

**Comment by ravahn** [comment]
Thanks for reporting, this is now fixed.   Both SAM and RDM were missed, but I had a copy/paste issue with the 4.0 upgrade so I skipped all the LB1s as well.  Going to close as fixed, and the full release is available now.
