### ISSUE TITLE
v1.5.1.0 Limit Break counting for person used, not separate anymore.

### ISSUE THREAD

**Issue by Mitsuma** [ravahn/FFXIV_ACT_Plugin#77]
Title describes it pretty much.
Used to show as its own entry, now its added to the persons dps who used it.

Not sure if thats caused by the Parse Filter which is set to "Party" at the moment because Alliance doesn't work.

**Comment by ravahn** [comment]
Hmm, which specific limit break was not being treated as separate?  I did a pass for 1.5.1.0 to fix them, all the LB1's and the SAM/RDM LBs were doing this for 1.5.0.4, but it should be fixed now.

**Comment by Mitsuma** [comment]
Yea, I noticed it on my BLM, on somebodies RDM and even on a friends NIN LB1.

**Comment by Mitsuma** [comment]
Think this fixed itself or was fixed by you.
