### ISSUE TITLE
Direct Hit/Critical Direct Hit variables?

### ISSUE THREAD

**Issue by Nararthok** [ravahn/FFXIV_ACT_Plugin#78]
I've been trying to figure this one by myself, but I haven't had any luck. What should I use to show the direct hit and critical direct hit %?
I see the DirectHitPct column, but it seems that's not the name I should use. Any help? Thanks!

**Comment by ravahn** [comment]
If you're asking about how to add these to an overlay like Rainbowmage, this requires an ACT variable be defined.  There isn't one yet, but it will be called DirectHitPct, possibly in the next version.

**Comment by Nararthok** [comment]
Oh, I see. ACT can show us the data on the screen, but there isn't a variable yet... No wonder I couldn't find it. Thanks!

**Comment by ravahn** [comment]
This is included in version 1.5.1.3, which was just released.  {DirectHitPct} and {CritDirectHitPct}.  the difference is the first  contains the percent of hits that are directhit, and the second contains percent that are both directhit and critical.
