### ISSUE TITLE
DPS over past n seconds

### ISSUE THREAD

**Issue by xijio** [ravahn/FFXIV_ACT_Plugin#8]
It'd be really cool to see 'current' dps vs 'encounter' dps.  So you could see during big pushes how high the dps is, say over the past 5-10 seconds.

**Comment by ravahn** [comment]
I've added ACT variables for 10 seconds, 30 seconds, and 60 seconds to the encounter and combatant which can be used to construct mini-parse format strings.  It doesn't seem to affect CPU usage when on a training dummy, but I haven't tested in a 24-man zone or for extremely long encounters..

This will go out with the v1.3.0.8 update.

**Comment by xijio** [comment]
Very cool!  Thanks a ton :)
