### ISSUE TITLE
v1.5.1.0 Issue with tracking spells in duties

### ISSUE THREAD

**Issue by robotiod** [ravahn/FFXIV_ACT_Plugin#82]
Looking at my parse of a recent Susano extreme my assize casts weren't being recorded. I'm not sure if there are other casts being missed for other classes as I wouldn't really personally notice but I know for certain assize was missing. That wasn't happening while parsing in the overworld. 

https://drive.google.com/file/d/0BxN-p4aybty0cW9ZZ3Z5dDA4ems/view?usp=sharing

Here's a link to the log in question.

**Comment by ravahn** [comment]
Looking into it, thank you for reporting it.  First time hearing of it.

**Comment by ravahn** [comment]
I found the culprit.  There are certain skills in certain situations which are using a rare packet that I didn't find during my earlier testing.  in one sample parse it occurred five times out of a 23MB log.  It probably just so happens that your casts of Assize, as well as a couple other casts in the log used this packet type.

Working on a fix, will try to finish it up and release an update tomorrow.

**Comment by ravahn** [comment]
This is fixed in 1.5.1.3, thanks again for reporting.
