### ISSUE TITLE
v1.5.1.3 - Tracking the new shields

### ISSUE THREAD

**Issue by Hozomeen** [ravahn/FFXIV_ACT_Plugin#85]
Currently, shielding done by Blackest Night (the new level 70 DRK ability) isn't being tracked. Would it be possible to count it like other shields are being counted? The skill creates a barrier around the DRK or another party member, equaling 20% or 10% of the DRK's HP.

On a related note, I just realized that Divine Benison, the new WHM shield, isn't being tracked either. It also creates a barrier based on max HP. Is this an issue with those kinds of barriers in general?

**Comment by ravahn** [comment]
I'll take a look, I have not added any of the new barriers.  Most things other than direct heals/damage have to be specifically coded in the plugin because the data sent by the game is usually missing information,

**Comment by Hozomeen** [comment]
I see, thank you for looking into it.

**Comment by ravahn** [comment]
Shields have been updated with the 5.0 changes, this will go out in the next release.
