### ISSUE TITLE
Encounter object is missing some items that are showing in combatant view 

### ISSUE THREAD

**Issue by christianallred** [ravahn/FFXIV_ACT_Plugin#88]
Namely direct hit, direct crit hit, crit types.

Also the heal critical percent is not getting tallied correctly in either the comabatnt objects or the encounter objects

**Comment by christianallred** [comment]
See this issue as reference 
https://github.com/RainbowMage/OverlayPlugin/issues/57

**Comment by christianallred** [comment]
I am sure there are more like this. These are simply the ones I found. I can look into the code base tomorrow and possibly submit a pr

**Comment by christianallred** [comment]
Oh never mind source code is private

**Comment by christianallred** [comment]
V1.5.1.3

**Comment by ravahn** [comment]
To re-word what you are saying - some data that is visible within ACT's main window is not exposed as ACT variables for overlays.  I will take a look.  All of the Crit data is coming from original ACT code except for DirectHeals Crit, so I don't know anything about inconsistencies with those variables.

**Comment by christianallred** [comment]
Yes when i got home from work today i will post what the object data that i am getting. 
I am writing a plugin overly for RainbowMages Overlay Plugin. And according to rainbow mage it is just grabing the objects from Your plugin. 

His overplay plugin grabs 2 variables per encounter. 

Encounter, Combatants(List)

Info in these two variables are inconsistant. 

The HealsCrit seams to be broken in ACT itself, an di can see that by looking in the combatants table so thats not really what this Issue is about. Although I found it as a side note. 

The real problem is what doesn't exist in the Ecounter object, that does exist on the individual Combatants Objects. 

Namely the items listed in the in the issue that i linked above. It is my understanding the Encounter object is simply a totaling of the combatants list items.

**Comment by Squall-Leonhart** [comment]
i turned off crit types and enabled critdam% and critheal% 
both work for the encounter view.

**Comment by christianallred** [comment]
Is critdam% exit damage / total damage or crit hits / total hits

**Comment by christianallred** [comment]
The later is much more useful

**Comment by ravahn** [comment]
It's the percent of crit hits, not crit damage.  from the original ACT code:
       return (float) ((double) this.CritHits / (double) this.Hits * 100.0);
for all outgoing damage

**Comment by christianallred** [comment]
Man that is poor naming... come on ACT

**Comment by ravahn** [comment]
Working on this still, but it requires careful testing unfortunately.  I'm not sure there is much value in general for encounter-level data for most players - is it useful to know the whole party's Direct Hit or overheal information vs. seeing it on the player level?

So, it may be a version or two before I add.

However, if you're writing an ACT plugin or have access to the Advanced_Combat_Tracker namespace in your Overlay plugin, you can add the encounter variables yourself.  Just be sure to make sure it was not already added by checking the key, i.e:

> if (!Advanced_Combat_Tracker.EncounterData.ExportVariables.ContainsKey("DirectHitCount"))
> {
> Advanced_Combat_Tracker.EncounterData.ExportVariables.Add(...)
> }

**Comment by christianallred** [comment]
Yeah no worries . I can actually roll it all up from the combatant list anyways. I just wanted to let you know it's missing

**Comment by ravahn** [comment]
Sounds good, thanks for the update.  I did add Combatant export variables to 1.5.1.4 (just released) in case they are useful, but am going to hold off on the encounter-level ones.
