### ISSUE TITLE
v1.5.1.4 CritDirectHitPct not working for overlays.

### ISSUE THREAD

**Issue by Mitsuma** [ravahn/FFXIV_ACT_Plugin#92]
Not sure what changed with the update but {CritDirectHitPct} doesn't seem to work anymore.

![advanced combat tracker_2017-06-28_14-18-08](https://user-images.githubusercontent.com/8568089/27636615-a4bbcace-5c0c-11e7-9c34-96d1eb41d940.jpg)

Worked fine in v1.5.1.3
I also made sure its correctly written as with the release notes.
`			{ text: "{crithit%}", width: "", align: "center" },`
`			{ text: "{DirectHitPct}", width: "", align: "center" },`
`			{ text: "{CritDirectHitPct}", width: "", align: "center" },`
Shows up correctly in the ACT main window.

**Comment by christianallred** [comment]
this is most likely an error with your overlay. plugin. If you are using rainbow mage, CritDirectHitPct is not getting imported properly through rainbowmage atm. 

see https://github.com/RainbowMage/OverlayPlugin/issues/58

**Comment by hibiyasleep** [comment]
OverlayPlugin [refers ExportVariables directly](https://github.com/hibiyasleep/OverlayPlugin/blob/master/OverlayPlugin.Core/Overlays/MiniParseOverlay.cs#L198), so this is not OverlayPlugin's bug. CritDirectHitPct seems just missing on ExportVariables in this release, since 1.5.1.3 worked fine.

**Comment by ravahn** [comment]
This is due to a bug related to decimal places and string / int conversion.  It will be fixed in the next release.

**Comment by ravahn** [comment]
This is fixed in release v1.5.1.5.
