### ISSUE TITLE
request: tracking for min and max

### ISSUE THREAD

**Issue by Firesped** [ravahn/FFXIV_ACT_Plugin#94]
is it possible to add tracking not just for min and max damage. but for min and max per hit type?

normal hit min and max
critical min and max
direct hit min and max
critical direct hit min and max

it seems to me that basing damage on an average of attacks that do far less damage for the min and a top damage that rarely goes off for the max is going produce false Average numbers.

example encounter: auto attack only testing
Time: 925 seconds
Damage: 472023
DPS: 510.3
Average: 1329.64
ACT reported min: 1138
ACT reported max: 2273
hits: 355
crit hits: 44
DH hits: 134
CDH hits: 14

I watched the game and pulled numbers as best I could. The parser should be able to track exact numbers though with ease.
hit min: 1138
hit max: 1258
AVG hit: 1198
DH min:  1433
DH max: 1568
AVG DH: 1500.5
crit min: 1698
crit max: 1863
AVG CRIT: 1780.5
CDH min: 2121
CDH max: 2273
AVG CDH: 2197

with my stats, 
DH seemed to be doing 25.25% more damage then hit avg.
CRIT was doing 48.62% more damage then hit avg.
CDH was doing 83.39% more damage then hit avg.

If we are trying to figure the effects of out secondary stats. these numbers seem more relevant then a global average damage.

**Comment by ravahn** [comment]
While I can see the value for this, it is not something I'm going to add it to the plugin.  ACT allows copying of swing data to CSV format on the clipboard, which can be pasted into MS-Excel or other spreadsheets and analyzed there.  ACT is a data collection tool and encounter analysis tool, and is not really designed for statistical analysis.  

You can already figure out min/max crit/DH values in ACT by looking at all swings, and sorting by damage column, then Crit, then DH, and then scrolling to the beginning/end of each region.

Lastly, there are some FFXIV theory crafters in discord who are working on statistical analysis, such as Dervy and Nemekh, I recommend getting in touch with them.  They have made great strides on collecting and analyzing data for DH/Crit/CDH and coming up with the multipliers for CRIT/DH/CDH.   I'm already using some of their results in ACT.
