### ISSUE TITLE
DirectHitCount / CritDirectHitCount

### ISSUE THREAD

**Issue by Atreyus** [ravahn/FFXIV_ACT_Plugin#97]
I have 1.5.1.5. and my ACT counts only CritDirectHitCounts for the DirectHitCounter. The DirectHitCounter
always has the same number like the CritDirectHitCounter.

**Comment by ravahn** [comment]
This may have been an early bug that I forgot to close.  I can see DirectHitCount & CritDirectHitCount columns on the Encounter, Combatant, and Category all show different values consistently now.
