### ISSUE TITLE
SMN Egi Damage

### ISSUE THREAD

**Issue by MirageBlader** [ravahn/FFXIV_ACT_Plugin#98]
Hey,
maybe it is already possible and if not would it be possible to have my SMN DPS and my Egi DPS combine AND also see my Egi DPS too. So the Egi is its own row in the parser with only Egi DPS but it still show mine combined. Sry for the poor english :) and thank you in advance

**Comment by ravahn** [comment]
This would have some ripple effects, such as inflating group DPS, and also complicate some internal tracking in ACT between swings and log lines, so I'm not going to implement it for now.
